### ISSUE TITLE
maven 打包好像有点问题

### ISSUE THREAD

**Issue by junbaor** [otale/tale#1]
* 使用 `maven package` 构建的不包含依赖包
* 使用 `mvn clean package assembly:single -Dmaven.test.skip=true` 构建的需要去 target\dist 下启动，且静态资源无法加载.

**Comment by biezhi** [comment]
fixed https://github.com/otale/tale/commit/522d3fd1d45fc3f578b8ba30a2bf79ae0d8f6428
