### ISSUE TITLE
界面:前台链接

### ISSUE THREAD

**Issue by SchuckBeta** [otale/tale#143]
目前开源版本是否只有后台，没有前台界面么？如果有前台页面链接是什么？为什么我访问的是无样式的

**Comment by biezhi** [comment]
https://tale.biezhi.me

**Comment by loo617** [comment]
同样的问题，前台界面样式显示不出来

**Comment by biezhi** [comment]
![image](https://cloud.githubusercontent.com/assets/3849072/23904108/ad9a02f4-0901-11e7-8a50-1bcdf395c8ad.png)
@loo617 这个看不到？
