### ISSUE TITLE
1.2.1 新特性规划

### ISSUE THREAD

**Issue by biezhi** [otale/tale#144]
- [x] 1. 支持富文本编辑器和markdown编辑器切换
- [x] 2. 主题配置选项，安装主题后无需重启
- [ ] 3. 可配置菜单，提供导航栏配置项
- [x] 4. 发布文章添加缩略图选项
- [x] 5. 优化主题函数

**Comment by huclengyue** [comment]
建议markdown编辑器使用这个https://pandao.github.io/editor.md/

**Comment by biezhi** [comment]
新版markdown编辑器使用了 https://github.com/Houfeng/mditor
editor.md太过重量级，依赖多

**Comment by biezhi** [comment]
- [x] 1
- [x] 4
- [x] 5
支持 `.html` 后缀访问

**Comment by huclengyue** [comment]
@biezhi 其实对我这种轻量编辑的人来说 editor.md 和mditor都一样，刚好之前用到 editor.md。现在看来我也要把之前的editor.md 换成mditor了 ^_^
