### ISSUE TITLE
model 类里面的变量可以改用驼峰命名的规则吗?

### ISSUE THREAD

**Issue by gchangyi** [otale/tale#146]
model 类里面的变量可以改用驼峰命名的规则吗（我对这个变量命名方式有点强迫症/doge /doge）

**Comment by dongm2ez** [comment]
模型中的变量与数据库字段密切相关，这里的变量更改是不好的

**Comment by biezhi** [comment]
目前还不可以，这是bladejdbc的一个约定，根据字段解析到数据库字段，如不这样做，需要在字段上使用注解标识字段，如实体里为userName，数据库为user_name，就需要在实体里指定字段名，不过我会将这个计划加入下一版本，实体信息都是根据数据库表结构生成出来的。
