### ISSUE TITLE
browsers block some content

### ISSUE THREAD

**Issue by locovna** [otale/tale#148]
At chrome, safari and firefox some files don't open because were loaded over HTTP:

`insecure stylesheet 'http://tale.biezhi.me/templates/themes/default/static/css/style.min.css'
insecure image 'http://tale.biezhi.me/templates/themes/default/static/img/logo.png'
insecure stylesheet 'http://tale.biezhi.me/templates/themes/default/static/css/style.min.css'`

So pages display completely without styles:
![screen shot 2017-03-06 at 11 30 32](https://cloud.githubusercontent.com/assets/15370225/23604462/9ebde968-0261-11e7-91e9-72fc794fe388.png)
<img width="935" alt="screen shot 2017-03-06 at 11 32 23" src="https://cloud.githubusercontent.com/assets/15370225/23604463/9ebea8a8-0261-11e7-90ce-9ff1f8c87982.png">
![screen shot 2017-03-06 at 11 34 53](https://cloud.githubusercontent.com/assets/15370225/23604464/9ec062ce-0261-11e7-9677-b1588a676d0d.png)

**Comment by biezhi** [comment]
Is that still true?

**Comment by locovna** [comment]
no, now everything looks fine  👀
