### ISSUE TITLE
回复评论有bug

### ISSUE THREAD

**Issue by JakeLaoyu** [otale/tale#152]
![image](https://cloud.githubusercontent.com/assets/16181940/23826198/85e10f86-06d2-11e7-9a63-84718fc4a3f3.png)

**Comment by biezhi** [comment]
这个截图是在哪里看到的？

**Comment by JakeLaoyu** [comment]
在 https://github.com/otale/theme_greyshade 这个主题中，我评论了一条，然后点击回复时

**Comment by biezhi** [comment]
fixed with https://github.com/otale/theme_greyshade/commit/6af0615be421634ebe21d23a935a0532de1aed85
