### ISSUE TITLE
用markdown写的文章在前台显示效果有

### ISSUE THREAD

**Issue by 81519434** [otale/tale#153]
![image](https://cloud.githubusercontent.com/assets/9690089/23831968/aa2748d0-0766-11e7-8662-4b96970bfa24.png)
上图为在后台编辑时的效果
下图为在前台显示的效果
![image](https://cloud.githubusercontent.com/assets/9690089/23831977/d2264caa-0766-11e7-9def-f90943781312.png)

**Comment by 81519434** [comment]
# 这样的大标题 前台识别不出来

**Comment by Sunzhuokai** [comment]
##之间空格

**Comment by 81519434** [comment]
![image](https://cloud.githubusercontent.com/assets/9690089/23832412/649e4ea0-076e-11e7-8f9d-93565368c090.png)
变成这样了，只支持一级标题吗？

**Comment by 81519434** [comment]
要保持 前台效果和后台预览的markdown效果一致才好啊

**Comment by huclengyue** [comment]
这个是你的markdown语法问题吧。。。

**Comment by 81519434** [comment]
# 一级标题
## 二级标题
### 三级标题
![image](https://cloud.githubusercontent.com/assets/9690089/23848122/a7385a38-0810-11e7-9fd5-3ffed2cce5ed.png)


你那个只支持1级标题。你可以试一试

**Comment by huclengyue** [comment]
应该没有问题的。我测试了一下 可以正常显示标题的。
![tim 20170313175516](https://cloud.githubusercontent.com/assets/9107717/23849372/57d17870-0816-11e7-98ee-95fd0c714f49.png)
![tim 20170313175448](https://cloud.githubusercontent.com/assets/9107717/23849377/5bc67516-0816-11e7-928d-09ca602c3e55.png)
