### ISSUE TITLE
文章作者和logo有配置的地方吗

### ISSUE THREAD

**Issue by 81519434** [otale/tale#154]
如题
![image](https://cloud.githubusercontent.com/assets/9690089/23832487/effe58f4-076f-11e7-9a54-b96dd0855410.png)

**Comment by Sunzhuokai** [comment]
目前在模板内写死的，可以自己定制模板修改

**Comment by biezhi** [comment]
fixed https://github.com/otale/tale/commit/da7fd30e7314af7b79bdee6b806588dfda008565
