### ISSUE TITLE
写的文章字数较多的情况下无法继续编辑，看看能不能使编辑的字数提升多点

### ISSUE THREAD

**Issue by AnneBlair** [otale/tale#166]

**Comment by AnneBlair** [comment]
好吧。超过5000啦😅

**Comment by AnneBlair** [comment]
好吧，显然是超过啦！😋

**Comment by biezhi** [comment]
😂 厉害了我的哥

**Comment by AnneBlair** [comment]
不对~~~~(>_<)~~~~。你看一下：[链接](https://juejin.im/post/58d24b2361ff4b006043fa0a )《字数1276》这么多内容不能在博客中却可以在 简书，掘金上面发表。😋

**Comment by Sunzhuokai** [comment]
5w包含样式这些，不是纯文字

**Comment by biezhi** [comment]
@AnneBlair 已经将字数调整至 `20w` ，你的那篇文章我测试一下，直接复制过来是 `10w+`
