### ISSUE TITLE
关注部署的问题

### ISSUE THREAD

**Issue by BigSnake1989** [otale/tale#171]
根据wiki的说明，将项目部署在liunx服务器上，通过xshell进行操作，通过tale.sh启动成功之后，如果关闭终端，服务也关闭了。这个应该如何设置呢。

**Comment by guitilangyin0000** [comment]
你需要以脱离终端的方式在后台运行这个shell命令。
方法如下：
（1）输入命令：
nohup 你的shell命令 &
（2）回车，使终端回到shell命令行；
（3）输入exit命令退出终端：
exit
（4）现在可以关闭你的终端软件了。
