### ISSUE TITLE
提供对管理员账号信息的修改

### ISSUE THREAD

**Issue by vzhilong** [otale/tale#176]
在管理界面可以提供对管理员账号信息的修改，比如显示名称、密码、邮箱之类的

**Comment by biezhi** [comment]
系统设置：`/admin/setting`

**Comment by vzhilong** [comment]
系统设置只能设置Blog信息、缓存信息以及备份信息，但是不能设置管理员账号信息。

**Comment by biezhi** [comment]
设置这些信息的作用是什么？
