### ISSUE TITLE
Markdown编辑后的文章，显示出来有格式问题

### ISSUE THREAD

**Issue by JeeseC** [otale/tale#181]
比如第一篇文章中，显示在前端，会把“#”直接显示出来，没有转换。
自己尝试过发表几篇文章，目前只发现“#”是不能够正常显示出来。

**Comment by biezhi** [comment]
第一篇文章的 `#` 是标题的CSS效果。
你输入
```markdown
# 标题
```
会显示为：
# 标题
前面会有个 `#` 这个是样式
