### ISSUE TITLE
文章编辑器“图片”工具

### ISSUE THREAD

**Issue by devotion987** [otale/tale#182]
tale里文章编辑时点击“图片”按钮想弹出框选择从本地上传图片功能，按照Mditor文档上说明，使用let btn = mditor.toolbar.getItem('image');却报错Uncaught TypeError: Cannot read property 'getItem' of undefined

**Comment by devotion987** [comment]
功能已实现，js代码如下
`mditor.on('ready', function() {
    	var upload = function(file) {
    		if (null == file)
    			return;
    		var name = file.name || 'screenshot.png';
    		name = name.replace(/\.(?:jpg|gif|png)$/i, ''); // clear ext
	        name = name.replace(/\W+/g, '_'); // clear unvalid chars
	        file.name = name;
	        var data = new FormData();
	        data.append('fileToUpload', file);
	        $.ajax('/admin/article/uploadToQiniu', {
	        	data : data,
	        	type : 'POST',
	        	processData : false,
	        	contentType : false
	        })
	        .done (function(res) {
	        	mditor.editor.insertBeforeText('![alt](' + res + ")\n");
	        })
	        .fail(function ($xhr) {
                if ($xhr.responseText) {
                    $.alert($xhr.responseText);
                }
            });
    	}
    	
    	//示例，更改「图片」按钮配置，其它按钮是同样的方法
    	var imgBtn = mditor.toolbar.getItem('image');
    	//替换按钮动作
    	imgBtn.handler = function(){
    		//自定义处理逻辑 this 指向当前 mditor 实例
    		// this.editor.wrapSelectText('![alt](', ')');
    		var accept = {
				image : 'image/png,image.gif,image/jpg,image/jpeg'
    		};
    		var $file = $('<input type="file" accept="' + accept.image + '">');
    		$file.click();
    		$file.on('change', function() {
    			var file = this.files[0];
    			upload(file);
    		});
    	};
    });
`

**Comment by eblly** [comment]
将修改提交到dev上

**Comment by devotion987** [comment]
@eblly  我自己拉了个分支，改动较大(改动部分：https://git.oschina.net/devotion/tale/issues)，将实现的代码贴出来供参考
`ArticleController`增加action方法
```
@Route(value = "uploadToQiniu", method = HttpMethod.POST)
@JSON
public String uploadImg(Request request) {
    Map<String, FileItem> fileItemMap = request.fileItems();
    for (Map.Entry<String, FileItem> entry : fileItemMap.entrySet()) {
        FileItem f = entry.getValue();
        String fname = f.fileName();
        if (f.file().length() / 1024 <= TaleConst.MAX_FILE_SIZE) {
            return QiniuUtils.uploadFile(f.file(), fname);
        }
    }
    return "";
}
```
QiniuUtils类代码如下：
```
public abstract class QiniuUtils {

    public static final String accessKey;
    public static final String secretKey;
    public static final String domain;
    public static final String bucket;

    static {
        Config config = $().bConfig().config();
        accessKey = config.get("qiniu.accessKey");
        secretKey = config.get("qiniu.secretKey");
        domain = config.get("qiniu.domain");
        bucket = config.get("qiniu.bucket");
    }

    /**
     * 上传图片到七牛云
     *
     * @param file
     * @param key
     * @return 返回图片链接
     */
    public static String uploadFile(File file, String key) {
        Auth auth = Auth.create(accessKey, secretKey);
        UploadManager uploadManager = new UploadManager();
        Response res = null;
        try {
            res = uploadManager.put(file, key, auth.uploadToken(bucket));
            if (res.isOK())
                String.format("http://%s/%s", domain, key);
        } catch (QiniuException e) {
            e.printStackTrace();
        }
        return "";
    }

}
```
app.properties文件增加七牛的相应配置，后续考虑截屏图片粘贴直接上传至七牛云
