### ISSUE TITLE
文章编辑问题

### ISSUE THREAD

**Issue by zxk175** [otale/tale#186]
没有保存按钮  有两个编辑框

https://zxk175.com/upload/2017/04/6f2ccrcidcg9kr1r4vqi8pkuke.png

有问题的文章是草稿

其他文章编辑正常

**Comment by eblly** [comment]
@zxk175 该问题如何重现.我无法重现你的截图的问题.

**Comment by zxk175** [comment]
![image](https://cloud.githubusercontent.com/assets/10259995/25303888/a0bf105a-278e-11e7-8b31-89c5735bfe23.png)

好像是js报的错

**Comment by biezhi** [comment]
试试新版本
