### ISSUE TITLE
[BUG]分页组件异常，出现负数

### ISSUE THREAD

**Issue by AnythingLucky** [otale/tale#188]
现在文章数量100左右，问题如下：    
![](https://ws1.sinaimg.cn/large/005NtUXTgy1feuas3tkpuj30ff01bdfl.jpg '')    
![](https://ws1.sinaimg.cn/large/005NtUXTgy1feuat72ls9j30gy01c0si.jpg '')

**Comment by AnythingLucky** [comment]
https://ws1.sinaimg.cn/large/005NtUXTgy1feuas3tkpuj30ff01bdfl.jpg
补上第一个图地址，就是出不来

**Comment by biezhi** [comment]
这个问题在 `1.2.15` 已经修复，你可以更新下程序试试，如果还有bug我继续跟踪这个问题
