### ISSUE TITLE
tale 初始化绑定了ip地址？

### ISSUE THREAD

**Issue by githublaohu** [otale/tale#19]
只能使用127.0.0.1请求到install，
但是我安装到 centos上的，无法得到页面。如何做。？
我没看到，端口与ip绑定的配置在哪里。

**Comment by biezhi** [comment]
默认使用的是 `127.0.0.1:9000` 

如果你想修改可以在 `app.properties` 中配置

- `server.port=9000` 设置端口
- `server.host=127.0.0.1` 设置主机

**Comment by githublaohu** [comment]
ok,
 如何进入管理界面啊。

**Comment by githublaohu** [comment]
发表的博客，无法看到。报404错误

**Comment by pkwenda** [comment]
@githublaohu 管理页面是你 http://ip:port/admin  账户密码是你install时候填写的
404错误方便截图吗？
可能是你本地运行，解析的站点名称导致的。

**Comment by githublaohu** [comment]
![o4b324 mf7lo 8 5 u0gb](https://cloud.githubusercontent.com/assets/8677242/23338566/6d0ce77a-fc49-11e6-92f7-d60ffaf8dbbd.png)
![Uploading 3(](FMX@WIWTV}31{U5@Y6B.png…]()

**Comment by biezhi** [comment]
@githublaohu  看起来很酷，遇到什么问题了吗？

**Comment by githublaohu** [comment]
点开 纪念2017.02026 报 404异常
