### ISSUE TITLE
编辑文章

### ISSUE THREAD

**Issue by xuaner0719** [otale/tale#190]
多次切换编辑器后，内容丢失。

**Comment by biezhi** [comment]
目前切换编辑器无法保存内容的，在下个版本我们尝试吧，因为 `html` 转成 `markdown` 无法完全兼容。

**Comment by tradetribe** [comment]
建议换成这个编辑器https://github.com/ckeditor/ckeditor5 @biezhi

**Comment by dongm2ez** [comment]
可以H5的local Storage 或者 session storage 对内容进行保存，切换时重新放入编辑框中

**Comment by biezhi** [comment]
@tradetribe 这个看起来还不错，但 [ace](https://github.com/ajaxorg/ace) 更酷，还是觉得简单点好 😄
