### ISSUE TITLE
不知道怎么部署这个博客系统

### ISSUE THREAD

**Issue by saigaobk** [otale/tale#197]
你好 我在网上看到了这个博客系统 觉得很好看 下载了这个tale这个代码 但是不知道怎么部署

**Comment by biezhi** [comment]
嗨，@saigaobk 不知道你是在什么环境下进行部署遇到问题了呢？可以向我们反馈吗？

**Comment by liuzhushaonian** [comment]
我特地在博客写了一篇部署教程，欢迎访问——http://www.legic.xyz/article/33

**Comment by fanhub** [comment]
你好，我在mac上部署你们最新版本的tale-master，运行sh tale.sh start后访问127.0.0.1:9000/install无效，不太明白原因。是不是因为下面这个error？
MeooldeMacBook-Pro:bin Meool$ sh tale.sh start
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
jarfile=
cmd: java -Xms128m -Xmx128m -jar  > ./tale.out < /dev/null &
Error: -jar requires jar file specification
用法: java [-options] class [args...]
           (执行类)
   或  java [-options] -jar jarfile [args...]
           (执行 jar 文件)
其中选项包括:
    -d32	  使用 32 位数据模型 (如果可用)
    -d64	  使用 64 位数据模型 (如果可用)

……
