### ISSUE TITLE
希望增加一些功能，如文章置顶

### ISSUE THREAD

**Issue by miyakowork** [otale/tale#201]
1、希望增加个文章置顶功能
2、希望增加导入的功能（顺带能够修改文章的发布时间，因为是导入以前的，所以需要修正为当时发布的时间）
3、希望博客的默认主题能够变为可手动设置的列数（现在为3列，我更希望4列。）
4、另外，希望能有个文字模式。也就是没有缩略图的显示的模式（图片显示好像有BUG，首页刷新时或者说是点击logo返回主页，图片会加载不出，ctrl+R重新加载页面有恢复）

**Comment by zoujiayu** [comment]
文章置顶功能，修改模板可以实现，就是设置置顶文章略麻烦

**Comment by biezhi** [comment]
#436
