### ISSUE TITLE
数据库会泄露管理员密码账号

### ISSUE THREAD

**Issue by starfire-lzd** [otale/tale#203]
hi：
    首先感谢您的博客系统
    我在使用过程中发现，在数据库的日志表中会用明文显示出登录时使用的密码账号，并且数据库并没有加密过，使用任意sqlate工具都可以直接读取

**Comment by biezhi** [comment]
hi @starfire-lzd ，感谢你提出的问题，已经得到修复，将会在 `1.3.0` 版本得到解决。
