### ISSUE TITLE
端口修改后部分生效

### ISSUE THREAD

**Issue by ingpf** [otale/tale#208]
按照这个链接的操作
https://github.com/otale/tale/wiki/7.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

可以用新端口访问，但是首页的样式无法访问，看控制台还是9000端口

**Comment by ingpf** [comment]
原因找到了，初始化的时候按照默认的端口号入库，停服，添加server.port=新端口号属性，导致配置表(t_options)里面的site_url上端口号和新设置的不一致

**Comment by biezhi** [comment]
@ingpf 😂不是bug，这个只能在安装的时候注意，因为程序无法读取到域名，所以输的是什么就存在数据库了。
