### ISSUE TITLE
Html页面静态化

### ISSUE THREAD

**Issue by caosg** [otale/tale#209]
看了下源码，好像没有实现html静态化；另外这个系统支持分布式吗？

**Comment by biezhi** [comment]
以 `.html` 为后缀算静态化还是真正意义的生成静态网页？
分布式目前不支持，不过可以考虑一下，感谢你的建议。

**Comment by dongm2ez** [comment]
这个已经无意义了，目前搜索引擎对于这个已经没有加权了
静态化是减少服务器压力，但对于个人博客意义真不大，如果喜欢这个可以直接用静态博客
伪静态化也没什么意义

**Comment by xiaoningboke** [comment]
网站地图怎么添加啊

**Comment by biezhi** [comment]
直接访问 `http://网址/feed` 就可以了，关于静态化在未来版本应该会加入直接发布到 github 上
