### ISSUE TITLE
public index page shows no graphics at my iphone chrome browser

### ISSUE THREAD

**Issue by larrydalaw** [otale/tale#213]
I did clone the project and run the script as instructed. working fine at browser but not in my iphone , though when i resize my mac osx browser to a small one it did show graphics, attached are the screen cap on my iphone.

thanks!
![img_2815](https://user-images.githubusercontent.com/22143918/28347770-a73e6f30-6c6b-11e7-9a3a-2f1cee36608b.PNG)
![img_2814](https://user-images.githubusercontent.com/22143918/28347771-a7404468-6c6b-11e7-8b88-736d17716163.PNG)

**Comment by biezhi** [comment]
1. the dashboard display on the mobile end has a bug, will fix it
2. home page style cannot show, you try on the PC what look at the request of the CSS address?
