### ISSUE TITLE
Markdown问题

### ISSUE THREAD

**Issue by zenuo** [otale/tale#220]
## 描述
使用Markdown书写超链接，当url含有右括号（")"）时，异常，如下

Markdown代码：
```
* [Covariant and contravariant](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science))
```
显示：
```
Covariant and contravariant)
```
实际url：
```
https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science
```
如图：
![](https://file.yziyz.xin:81/scrnst20170821175644.png)

**Comment by biezhi** [comment]
这是一个markdown渲染的bug，我会将它提交到 [commonmark](https://github.com/atlassian/commonmark-java)

**Comment by yziyz** [comment]
好的，谢谢。

2017年9月3日 下午8:38，"王爵nice" <notifications@github.com>写道：
