### ISSUE TITLE
中文乱码 问题

### ISSUE THREAD

**Issue by dowhilenet** [otale/tale#223]
在服务器上进行了简单搭建 [地址](http://118.89.38.191:9000)

![image](https://user-images.githubusercontent.com/10379476/30051845-1a89346e-91e9-11e7-9b3b-8231af0ef452.png)

**Comment by biezhi** [comment]
下载新版本试试

**Comment by dowhilenet** [comment]
@biezhi 我下载的是最新版本1.3.1

**Comment by biezhi** [comment]
试试 [下载](http://7xls9k.dl1.z0.glb.clouddn.com/tale-1.3.0-alpha1.zip?v=20170907) 这个版本，这个问题已经得到修复
