### ISSUE TITLE
文章如何自定义多级目录

### ISSUE THREAD

**Issue by juemuren4449** [otale/tale#225]
例如文章的默认访问链接是http://juemuren4449.com/article/xxx，
怎么修改article为自定义目录并且支持多级目录，
例如http://juemuren4449.com/blog/xxx，
http://juemuren4449.com/blog/day/xxx
谢谢！

**Comment by biezhi** [comment]
可以根据分类来，如 `http://juemuren4449.com/category/第三方集成` 。
目前不支持直接定义目录
