### ISSUE TITLE
最新的master分之代码tale-cli执行报错

### ISSUE THREAD

**Issue by dreamoftch** [otale/tale#236]
mac下拉去最新的代码master分之(commit:8ddf1eaea8930a66415f79f308e3db8771a6c49b)
在根目录执行命令
./tale-cli start
报错：exec format error: ./tale-cli
是我姿势不对吗

**Comment by dreamoftch** [comment]
通过java -jar xxx.jar的方式是可以正常启动的

**Comment by biezhi** [comment]
嗨 @dreamoftch ，tale 项目 `bin` 目录下的可执行文件是针对于Linux操作系统的，在mac平台下可以通过 `brew install tale-cli` 进行安装。这个项目的介绍在：https://github.com/otale/tale-cli
