### ISSUE TITLE
不少 php-fpm 进程都会默认占用 9000端口, 这个可以自定义吗 ?

### ISSUE THREAD

**Issue by gclove** [otale/tale#249]
不少 php-fpm 进程都会默认占用 9000端口, 这个可以自定义吗 ?

**Comment by dowhilenet** [comment]
可以在配置文件中修改。

**Comment by gclove** [comment]
不好意思哈, 我对java不是很熟悉

我只是看了下` tale release` 文件, 除了 .jar 和 一些HTML 相关的文件

好像没有， 例如  `conf` ,  `yaml`, `ini`, `enc` 之类的文件 ...

---

难道你指的是修改 php-fpm 的端口 ? @dowhilenet

**Comment by dowhilenet** [comment]
@gclove 你可在 resources 文件下修改 app.properties 文件 添加 server.port=9001

**Comment by gclove** [comment]
👍 赞 @dowhilenet 

@biezhi  我觉得这个很重要, 应该加入wiki, 和默认配置文件

**Comment by dowhilenet** [comment]
@gclove tale 是基于 [balde](https://github.com/biezhi/blade) 开发的，你可以去看看 blade 的文档。那里会将的很清楚。

**Comment by biezhi** [comment]
@gclove 在wiki中有提到如何修改端口了，在 [这里](https://github.com/otale/tale/wiki/7.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
