### ISSUE TITLE
[新特性] 后台编辑和新增模板

### ISSUE THREAD

**Issue by biezhi** [otale/tale#250]
管理后台提供编辑当前主题模板，新增自定义模板功能

**Comment by dowhilenet** [comment]
![](http://7s1rp2.com1.z0.glb.clouddn.com/1QW5JD375CTI_%7DEB7UK6KGD.png)

升级之后编辑页面404

**Comment by biezhi** [comment]
建议全面升级一下，因为修改了 `admin` 中的页面结构，使用 `tale-cli` 是不会更新模板文件的（因为部分用户是自定义的）

**Comment by dowhilenet** [comment]
@biezhi ok thanks

**Comment by dowhilenet** [comment]
@biezhi 请问一下。您所说的全面升级是怎样进行升级的？之前的数据会不会丢失。

**Comment by biezhi** [comment]
不会的，对于用户而言最重要的是 `tale.db`（数据库文件），以及自定义文件（比如LOGO，如果有的），和 `upload` 中上传的文件（如果有的话），其他都无关紧要。
