### ISSUE TITLE
请问前端页面能有不用cdn的版本吗？

### ISSUE THREAD

**Issue by zhenfeng-zhu** [otale/tale#253]
我们是在局域网里面部署，没有办法去访问外网，所以CSS样式全乱了

**Comment by biezhi** [comment]
这个需要修改一点源码了，因为都不带CDN的话大家要多下载一些文件，这对大多数用户而言是不必要的。
如果你需要修改我可以告诉你有哪些地方，这样可以吗？

**Comment by zhenfeng-zhu** [comment]
应该只是resource文件夹下面那些是cdn开头的东西吧，我这几天抽空整理一下吧

**Comment by biezhi** [comment]
fixed https://github.com/otale/tale/wiki/7.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E9%97%AE%E9%A2%98%E6%88%91%E4%B8%8D%E6%83%B3%E4%BD%BF%E7%94%A8cdn
