### ISSUE TITLE
使用 Tale 的博客在此列出 :)

### ISSUE THREAD

**Issue by pkwenda** [otale/tale#26]
- 如果你的博客是用 Tale 搭建的，欢迎在此列出

**Comment by biezhi** [comment]
这个想法应该列在wiki中

**Comment by damozushi** [comment]
腾讯云+Window

**Comment by Lemonjing** [comment]
感觉程序员使用静态博客就可以了啊，轻量便捷

**Comment by biezhi** [comment]
@Lemonjing 静态博客基本就是 hexo，jekyll，很多java程序员还是不愿意接受的，当然Tale是除此之外的一个选择。

**Comment by joutaojian** [comment]
静态博客大多用github.io，访问太慢了。
还是用Tale吧，就是每年要给点服务器费和域名费。

**Comment by Lemonjing** [comment]
@joutaojian 我之前也是网站 阿里云低配98元/月。学生党真是用不起了。GitHub Pages 写静态的话，访问还是可以的。

**Comment by huclengyue** [comment]
在使用ghost blog 想换 。。这个不错 刚好我也是做android的还可以自己修改一下，唯一疑问就是主题能不能https://apkdv.com/这种的？我比较喜欢这种

**Comment by pkwenda** [comment]
@huclengyue 你的网页打不开哦

**Comment by maoturing** [comment]
@Lemonjing  可以试试腾讯云，学生认证有很大的优惠

**Comment by Soso-zyc8** [comment]
我也用了 ，可是有些小问题http://139.129.240.159/

**Comment by biezhi** [comment]
@Soso-zyc8 访问不了

**Comment by gchangyi** [comment]
上周末成功部署www.rootage.me，tale非常简洁易用

**Comment by Soso-zyc8** [comment]
@biezhi   之前刚买的 服务器，一直在搭建测试阶段，现在好了  可以访问了。 打算做些修改。比如页签不能下拉，屏幕没有树状结构...等等，这些。

**Comment by fzweclipse** [comment]
哪位能提供一下windows部署的方案吗？

**Comment by huclengyue** [comment]
@fzweclipse 你下载最新版直接java -jar tale-1.2.0.jar就好了

**Comment by Barry1990** [comment]
我觉得可以把博客做成一个docker镜像 这样就能一键部署了

**Comment by leonardocsc** [comment]
用tale搭了个博客，http://leizhi.xiake.tech/

**Comment by istrwei** [comment]
http://123.184.34.156/

**Comment by zxk175** [comment]
用tale搭了个博客，http://zxk175.com

**Comment by eblly** [comment]
www.eblly.com

**Comment by coderspike** [comment]
http://182.61.24.26/

**Comment by qq434595824** [comment]
http://119.29.173.41:9000

**Comment by L-Gravel** [comment]
vultr主机+tale
http://www.gravel.site/

**Comment by abbywind** [comment]
腾讯云+tale
http://www.abbywind.cn

**Comment by Javawuyanbo** [comment]
阿里云+tale
www.laolatiao.cn

**Comment by bankly** [comment]
www.zweibok.com

**Comment by dowhilenet** [comment]
dowhile.net

**Comment by tuzhao** [comment]
[tuzhao.org](https://tuzhao.org)

**Comment by VeirPandan** [comment]
[https://www.veir.site](https://www.veir.site)

**Comment by afx919** [comment]
http://blog.afx919.com/[http://blog.afx919.com/](url)

**Comment by wuao** [comment]
http://120.78.157.244:9000/  moretime的博客 域名尚在备案中 博客内容也在迁移  阿里云centOs7 部署的

**Comment by VeirPanda** [comment]
服务器部署Tale[教程](https://www.veir.site/article/how-to-install-tale)

**Comment by VeirPanda** [comment]
服务器部署Tale全过程,[地址](https://www.veir.site/article/how-to-install-tale)

**Comment by githubforyour** [comment]
先占个楼 www.itviki.com  稍后送上！

**Comment by biezhi** [comment]
@githubforyour 兄弟，地方占错了，在 https://github.com/biezhi/blade/issues/144

**Comment by jaytangchn** [comment]
我也来凑个热闹: http://jaytang.me

**Comment by biezhi** [comment]
@jaytangchn [这里](https://github.com/biezhi/blade/issues/144) 来一发

**Comment by MaRuifu** [comment]
http://maruifu.cn

**Comment by dzy0302** [comment]
源博客 http://twojz.top

**Comment by zealzhangz** [comment]
个人博客：https://www.zhangaoo.com

**Comment by a100488** [comment]
songaw.com

**Comment by a100488** [comment]
[](http://www.songaw.com)

**Comment by a100488** [comment]
我的技术博客[http://www.songaw.com](http://www.songaw.com)

**Comment by mmclickmax** [comment]
https://androidblog.linghit.com/  我们团队大安卓的博客~

**Comment by iminto** [comment]
https://www.baidecai.com/

**Comment by p1094358629** [comment]
域名还在备案.目前用的这个,稍微修改了下布局http://111.231.92.230:9000

**Comment by p1094358629** [comment]
11

**Comment by onlyloveyd** [comment]
http://onlyloveyd.cn/

**Comment by zoujiayu** [comment]
https://blog.2aa.win

**Comment by anybboo** [comment]
https://anybbo.com

**Comment by zhaoweih** [comment]
http://zhaoweihao.com

**Comment by 775854115** [comment]
原本也是用的tale,还是很不错的。。不过因为服务器的原因，我又重新回到github上了
https://deren.ml

**Comment by MuenYu** [comment]
个人博客 https://muz1.xyz

**Comment by denganliang** [comment]
https://denganliang.com

**Comment by PineHunter** [comment]
https://www.ihesong.cn

**Comment by x163maiaytang** [comment]
http://123.56.98.62    阿里云  域名还在备案中

**Comment by wqrqwerqrw** [comment]
腾讯云 + tale

www.wqrblog.xyz

**Comment by huclengyue** [comment]
@wqrqwerqrw  明明是WordPress

**Comment by wadeChen0915** [comment]
[http://blog.clearcode.top/](http://blog.clearcode.top/)  阿里云 + tale

**Comment by zhoriya** [comment]
https://www.52zhoujia.cn/ 新开的博客，基于tale，自己写插件
