### ISSUE TITLE
无法评论以及无法上传文件

### ISSUE THREAD

**Issue by liuzhushaonian** [otale/tale#261]
新版本无法评论，以及无法上传图片。这些都不是重点，重点是编辑过后的自动保存会另外保存一份，而不是替换原有的，这样在发表之后，突然发现列表里还有一份是未发表的，是自动保存的结果。越修越多bug了。希望能恢复1.12时候，稳定而又无太多bug

**Comment by biezhi** [comment]
fixed https://github.com/otale/tale/pull/263
