### ISSUE TITLE
编写插件

### ISSUE THREAD

**Issue by starfire-lzd** [otale/tale#265]
编写插件的方式是发生了变化是么？初始化插件的时候怎么向设置界面添加item呢，文档中的方式好像不行了，WebContextListener类无法找到了

**Comment by biezhi** [comment]
嗨 @starfire-lzd ，编写插件的 [wiki](https://github.com/otale/tale/wiki/6.-%E6%8F%92%E4%BB%B6%E7%BC%96%E5%86%99) 中更新了类名。
