### ISSUE TITLE
mysql数据库的支持问题

### ISSUE THREAD

**Issue by happyshrm** [otale/tale#267]
请问现在最新的最新版本是不支持MySQL了吗

**Comment by dongm2ez** [comment]
最新版使用的是sqllite，sqllite和mysql在常用功能上基本一致，也许可以考虑增加功能在安装时做选择数据库

**Comment by happyshrm** [comment]
重启服务器之后，数据会丢失，如果是sqllite的话

**Comment by happyshrm** [comment]
我试过一次，然后后面就没再怎么用了，blade的设计感觉很赞，学完spring之后一直想研究底层实现，但spring又很重

**Comment by biezhi** [comment]
嗨 @happyshrm ，重启服务器后数据会丢失这个是不存在的，在开发者环境下可能会遇到。
学习 Blade 可以从 [README](https://github.com/biezhi/blade/blob/master/README_CN.md) 或者 [官网](https://lets-blade.com) 得到更多。
