### ISSUE TITLE
文章编辑保存多次草稿

### ISSUE THREAD

**Issue by tuzhao** [otale/tale#270]
我在后台编辑已经发布过的文章，按正常的逻辑应该是文章的草稿始终只保存一次，为什么会保存多次呢？

如果保存多次的逻辑是正常的，那么假如一篇文章为https://xxx/article/5，那么点击保存文章按钮应该还是提交到5这个id上，可是为什么保存到最后一次草稿的id上了，假如最后一次草稿的id为10，那么这篇已经发布过的文章链接就变成了https://xxx/article/10。如果第三方引用了id为5的文章链接，那么现在打开id为5的文章链接就404了....

**Comment by tuzhao** [comment]
![screenshot from 2017-10-11 23 44 37](https://user-images.githubusercontent.com/9989910/31451672-47eec2d0-aedf-11e7-8bb1-5daea554976c.png)

**Comment by biezhi** [comment]
新版本已修复
