### ISSUE TITLE
后台黑名单功能

### ISSUE THREAD

**Issue by biezhi** [otale/tale#28]
部分ip产生垃圾评论，禁止访问

**Comment by Yifei0727** [comment]
评论可否做成外挂式？
这样的话可以选择一些现存的评论系统具体啥名我就不说了。
有时候自带的局限太多。

**Comment by biezhi** [comment]
@Yifei0727 外挂式是什么样

**Comment by pkwenda** [comment]
应该类似```多说```

**Comment by Yifei0727** [comment]
是的，百度下好多的。
`多说` `畅言` `友言` 等

**Comment by Yifei0727** [comment]
我单独开个Issue吧。

**Comment by Yifei0727** [comment]
黑名单我看在 `tale\src\main\java\com\tale\interceptor\BaseInterceptor.java` 中有相关记录
```java
 public boolean before(Request request, Response response) {

        String uri = request.uri();

        LOGGE.info("UserAgent: {}", request.userAgent());
        LOGGE.info("用户访问地址: {}, 来路地址: {}", uri, IPKit.getIpAddrByRequest(request.raw()));
```
黑名单IP是单独弄张数据库表存储吗？

**Comment by biezhi** [comment]
这里记录的是日志打印，黑名单是对某些恶意频繁访问和垃圾评论在后台手动添加，系统自动返回错误码

**Comment by biezhi** [comment]
move https://github.com/otale/tale/issues/87 close https://github.com/otale/tale/issues/28
