### ISSUE TITLE
md编辑出现bug

### ISSUE THREAD

**Issue by starfire-lzd** [otale/tale#280]
md的cdn不能用了，关闭cdn之后整个后端界面错乱

**Comment by biezhi** [comment]
升级一下就可以了，又拍云的 `CDN` 服务到期了

**Comment by starfire-lzd** [comment]
https://o7d6mdbet.qnssl.com/css/mditor.min.css 这个返回478；
禁用了cdn整个界面就错乱了

**Comment by starfire-lzd** [comment]
在CDN的里面的md编辑器的css文件路径加的有问题，少写一段地址

**Comment by biezhi** [comment]
目前已经将资源文件打包在本地了，不走CDN了
