### ISSUE TITLE
菜单栏不可改变

### ISSUE THREAD

**Issue by eblly** [otale/tale#287]
首页菜单栏似乎是固定的。后台编辑不生效

**Comment by eblly** [comment]
应该是：首页并没有标签分类功能。

**Comment by biezhi** [comment]
默认的主题没有设计 **标签** **分类** 列表。
菜单可以在编辑模板的位置修改，目前还没做定义菜单功能

**Comment by alisonY** [comment]
后台修改模板后，查看./resources/templates文件下的文件确实有变动，但是页面上并没有生效，是因为展示页面用的是jar包中的文件？

**Comment by biezhi** [comment]
@alisonY 前端的页面展示就是模板文件，即时生效的。

**Comment by biezhi** [comment]
@alisonY 亲测可以
