### ISSUE TITLE
支持后台修改文章发布时间

### ISSUE THREAD

**Issue by biezhi** [otale/tale#290]

**Comment by dongm2ez** [comment]
尝试修改了，但是遇到问题，好像跟框架有个，框架会自动解析请求参数，但是再传的过程中所有值都是被当做字符串处理，而在程序内设置是int，所以会发生异常，这个值外部根本设置不了

**Comment by biezhi** [comment]
是这样的，后台使用 `unix` 时间戳存储的，所以会有这个问题，要么前端输入时间后将 **字符串时间** 转为 **时间戳** 传递到后台，要么后台添加一个字段做解析，回头想起来时间戳这个设计确实不太符合。。。

**Comment by dongm2ez** [comment]
我已经尝试在前端转换为时间戳了，但是传输到服务端还是认为它是string，不是int，不知道怎么改了，抛出的异常堆栈也全部是在框架层面

**Comment by biezhi** [comment]
那可以暂时修改为 

```java
@PostRoute(value = "modify")
@JSON
public RestResponse modifyArticle(@Valid Contents contents, @Param Integer someTime) {
}
````

这样的方式传递，我看下为什么服务端接收的是 `string` 类型。
