### ISSUE TITLE
css样式无法加载

### ISSUE THREAD

**Issue by liunianbanbo** [otale/tale#291]
本地可以访问，测了在同局域网下无法加载。连上外网一些cdn的js样式可以加载，但是css样式一个没有，这个是哪方面的问题
![fedora 64 -2016-10-29-10-57-35](https://user-images.githubusercontent.com/15794903/32140404-7f905e56-bc9a-11e7-97bf-ec88c245644a.png)

**Comment by liunianbanbo** [comment]
我放倒外网服务器也是一样，无法加在css样式
http://23.105.217.75:9000/

**Comment by biezhi** [comment]
嗨 @liunianbanbo ，你下载的版本是新的吗？

**Comment by liunianbanbo** [comment]
是最新版的，昨天和今早照着wiki做的。
在本地访问正常，局域网和外网访问就缺少css样式了
抱歉我不大会java不知道在哪里修改所以提了个issue

**Comment by biezhi** [comment]
我看不到你在外网的地址

**Comment by MuenYu** [comment]
mysql版本首页无法获取css、js等静态资源，但后台管理没有问题
