### ISSUE TITLE
自定义访问路径出问题

### ISSUE THREAD

**Issue by veir-panda** [otale/tale#294]
# 问题描述
1. 发布文章填写了自定义访问路径，但在实际访问时确无法无法访问，所有的文章在首页查看、后台编辑时打开都不是原本的文章，新添加了一个“友链”页面，打开也变成了“关于”的页面。查看tale.db数据库文件发现所有文章数据均正常。
2. 后台文章编辑将自定义访问路径删除后保存，再打开还是会存在。

# 问题重现
我之前用的是tale-1.2.15版本，昨天（2017.10.29）晚上新换了服务器就重新下载了最新版本，版本号未知，使用Nginx代理，重新部署好以后，将原tale/resources/下的upload和tale.db复制到了新的resources目录下，测试的时候最开始正常，但是在点了一些链接，大概2分钟之后出现问题。之前的版本未发现此问题。

# 其他：
尝试过重启tale和重启服务器，没有效果。
这是我的服务器[地址](https://www.veir.site/)，可以访问查看具体的错误体现。暂时保留此状态几天，打算过几天恢复旧版本。

**Comment by biezhi** [comment]
嗨 @veir-panda ，感谢你的反馈，当前的版本修复了之前的一些问题，我看了你的站点没有做复杂的修改，建议你进行全量升级。
1. 备份 `resources/tale.db`（存储了你的文章）
2. 备份 `upload` 目录（存储了你上传的图片）
然后重新安装新版本即可

**Comment by veir-panda** [comment]
@biezhi  群主，这是我昨天晚上才下的最新版本唉，而且就是按你说的只对`upload`和`tale.db`做了覆盖。你这么快就改好了？

**Comment by biezhi** [comment]
没有任何修改，我昨晚也演示过了，没有问题啊

**Comment by biezhi** [comment]
在新版本中友联页面设置成了后台可编辑的 `页面`，不是之前的静态页面了

**Comment by veir-panda** [comment]
是的，昨天晚上我自己新添加了一个友链页面，刚开始访问没问题，过一会儿就出现了访问文章错乱的问题。。。

**Comment by veir-panda** [comment]
算了，今天晚上回去我再重新试下看看

**Comment by biezhi** [comment]
好的，有什么问题可以在这里或者QQ询问

**Comment by dzy0302** [comment]
请问@biezhi 群主的QQ或者QQ群号是多少呢？我有些问题想请教一下

**Comment by biezhi** [comment]
群 1013565

**Comment by biezhi** [comment]
这个问题已修复，更新版本就可以了，这个 issue 关闭了
