### ISSUE TITLE
页面管理出现问题。

### ISSUE THREAD

**Issue by OuGaoJun** [otale/tale#295]
Windows server部署。
从这里下载的：http://static.biezhi.me/tale-least.zip?10281

我的网址是：www.ougaojun.com

问题：点击关于，跳转到www.ougaojun.com/about，出现404，而且404页面缺少了css样式，需要刷新才有完整的css。在后台管理里面的页面管理已经确认添加了about页面。也尝试过添加其它页面，比如about2，当时是可以访问，过了一会又不行了。

**Comment by OuGaoJun** [comment]
刷新前：
![image](https://user-images.githubusercontent.com/31914181/32184458-41c290e2-bdd7-11e7-9b50-a2c8a92685ba.png)
刷新后：
![image](https://user-images.githubusercontent.com/31914181/32184475-4fa5c116-bdd7-11e7-891b-d0a717e2def9.png)

**Comment by OuGaoJun** [comment]
在页面管理是确实存在这个页面的：
![image](https://user-images.githubusercontent.com/31914181/32184524-70dd4980-bdd7-11e7-9247-e069b0e9f6a4.png)

**Comment by biezhi** [comment]
嗨 @OuGaoJun ，感谢你的反馈，这个问题已经得到修复，你尝试更新一下，如果没有写内容重装更快。

**Comment by OuGaoJun** [comment]
@biezhi 弱弱地问一下，在Windows下怎么直接更新？

**Comment by biezhi** [comment]
@OuGaoJun 下载新包，解压后将 `tale.db`，`install.lock`，`upload` 目录复制到 `resources` 目录下重新启动即可。

**Comment by OuGaoJun** [comment]
@biezhi 非常感谢，已解决。
