### ISSUE TITLE
附件删除问题

### ISSUE THREAD

**Issue by dzy0302** [otale/tale#297]
最新打包的Tale，在附件删除一张图片时（试过不同格式的图片），显示删除失败，刷新一下页面，网页上没有那个附件了，不过在upload文件夹里还是发现了这张图片，并没有删除，请问是WIN10权限的锅吗？

**Comment by dzy0302** [comment]
在后台的问“文件管理”

**Comment by biezhi** [comment]
是个 `BUG` 已修复
