### ISSUE TITLE
markdown的显示问题

### ISSUE THREAD

**Issue by OuGaoJun** [otale/tale#298]
大佬又有问题了，在编辑的时候是非常的正常的，但是发布后就完全不一样了。
![1](https://user-images.githubusercontent.com/31914181/32229123-1680438e-be8b-11e7-8ce4-1ad6e25ed954.jpg)

![2](https://user-images.githubusercontent.com/31914181/32229138-1cefa7fa-be8b-11e7-8a52-f33b327bd75e.jpg)

还有，文章存为草稿的时候，再回去编辑会不显示，不知道是啥问题。
![3](https://user-images.githubusercontent.com/31914181/32229371-97d24c16-be8b-11e7-921a-837723a28673.jpg)

**Comment by biezhi** [comment]
嗨 @OuGaoJun 

第一个问题是因为你编写的 `markdown` 语法不标准导致，具体可以参考 [markdown语法说明](http://wowubuntu.com/markdown/)。

第二个问题尝试刷新一下，可能是JS没加载完全。

**Comment by OuGaoJun** [comment]
@biezhi 感谢大佬的回复，确实是有一些语法不对。
但是预览的时候却非常舒服。有些奇怪，哈哈。
还有，我很喜欢这个博客系统，谢谢biezhi大佬。

**Comment by biezhi** [comment]
@OuGaoJun 共勉，天色已晚，早休息。
