### ISSUE TITLE
CDN静态资源无法使用

### ISSUE THREAD

**Issue by leven-space** [otale/tale#300]
![tim 20171101231653](https://user-images.githubusercontent.com/31175045/32281763-c5a006e0-bf5a-11e7-92aa-799adaeecabe.png)

**Comment by biezhi** [comment]
请使用最新版本

**Comment by leven-space** [comment]
已经使用最新版本1.3.1

**Comment by biezhi** [comment]
新版本是 `tale-least.zip` 这个包，试试
