### ISSUE TITLE
Can I export a war and running into Tomcat

### ISSUE THREAD

**Issue by Aidenboss** [otale/tale#301]
For the title, Can I export a war and running into Tomcat?

**Comment by biezhi** [comment]
hi @Aidenboss , tale is a blog system developed by [blade](https://github.com/biezhi/blade), the project structure is a common
maven, built-in web server, you need to put it in the operation of the Tomcat container, you can view the [wiki](https://github.com/otale/tale/wiki) more, thanks 😃

**Comment by Aidenboss** [comment]
Thanks a lot
