### ISSUE TITLE
关于t_options的数据封装问题

### ISSUE THREAD

**Issue by JohnnyWu9712** [otale/tale#304]
想知道后台是如何把 `t_options` 表封装的，供前台调用，比如 `${theme_url()}` 

我看到封装的 `map` 在 `WebContext.java` 文件中的：

```java
Map<String,String> options = optionsService.getOptions();
TaleConst.OPTIONS.addAll(options);
```

**Comment by biezhi** [comment]
`${theme_url()}` 是模板引擎提供的一种函数机制，所有的函数都在 `WebContext` 类初始化的时候加载，函数存储在 [Commons.java](https://github.com/otale/tale/blob/master/src/main/java/com/tale/extension/Commons.java) 和 [Theme.java](https://github.com/otale/tale/blob/master/src/main/java/com/tale/extension/Theme.java) 文件中，他们均可以在模板中任意位置调用。
