### ISSUE TITLE
关于Https

### ISSUE THREAD

**Issue by dzy0302** [otale/tale#305]
申请了SSL证书，请问tale支持https协议吗？或者需要在源码里改些什么来开启https?

**Comment by biezhi** [comment]
嗨 @dzy0302 ，tale 是由 Blade 框架开发，目前不支持配置 `HTTPS` ，不过你可以使用 `nginx` 来完成这个，我也会考虑在未来版本是否支持直接配置 `HTTPS`。

**Comment by dzy0302** [comment]
您的意思是，我即使在WIN7服务器添加了443端口的SSL证书，我把tale的发布端口从9000改成443开启https也是没用的对吗？

**Comment by biezhi** [comment]
是的，一般也不会这么干，如果你将一个 web 站点修改为 `80` 或者 `443` 那么该服务器也只能有一个 `http` 或者 `https` 的网站。

**Comment by dzy0302** [comment]
明白了，谢谢解答！
