### ISSUE TITLE
页面链接错误

### ISSUE THREAD

**Issue by dzy0302** [otale/tale#309]
博客地址：http://twojz.top
使用的是最新版的tale完整包
把博客重启，按顺序点击三篇文章一遍，没问题，页面指向正常。
第二遍点击，三篇文章点什么都指向第一篇。

**Comment by dzy0302** [comment]
之前有一个版本是有同样的问题的，后来修复了，现在最新的版本又重现这个问题了

**Comment by biezhi** [comment]
```bash
./tale-cli upgrade
```

**Comment by dzy0302** [comment]
更新了最新打包版本，情况依旧。旧版的master开发环境没有这个问题

**Comment by dzy0302** [comment]
最新版，CPU占用率刚运行时占用0.5%左右，点开几个网页后上升到13%且居高不下，LOG并没有任何更新和错误

**Comment by biezhi** [comment]
我在服务器环境下无法重现 CPU 占用到 `13%`，目前 https://tale.biezhi.me 使用的是最新版本，CPU占用在 `1% - 5%` 左右。

**Comment by dzy0302** [comment]
我重启电脑后暂时就没问题了，不过页面还是错的，现在是全部指向“音乐分享”那篇博客

**Comment by dzy0302** [comment]
地址栏里显示的地址是正确的，但显示的页面是错的

**Comment by biezhi** [comment]
我继续排查这个问题

**Comment by biezhi** [comment]
fixed https://github.com/otale/tale/commit/d437500971ec1c4936aa95c29e881b3f332b8cb7

**Comment by dzy0302** [comment]
问题已解决！
