### ISSUE TITLE
读取markdown文件作为文章

### ISSUE THREAD

**Issue by HWYWL** [otale/tale#311]
大佬我觉得可以在发表文章的时候可以选择读取markdown文件作为文章的来源，好多笔记软件可以导出这个格式的文件方便转移（我的就是，手动滑稽）,希望（女装）大佬下个版本能考虑。

**Comment by notobject** [comment]
这个不错,我也支持! 或者改天我研究下 提交个Pull request

**Comment by biezhi** [comment]
可以把你的想法描述的详细一些吗？

读取 `markdown` 本地文件？网络URL？
支持导出 `markdown` 文档？
