### ISSUE TITLE
install.lock这个文件在哪儿

### ISSUE THREAD

**Issue by molq** [otale/tale#312]
安装完之后它说已经安装过了,要删除这个文件,但我找不到这个文件在哪儿

**Comment by OuGaoJun** [comment]
你安装的tale目录下有个resources文件夹，打开里面就能看到了。
![image](https://user-images.githubusercontent.com/31914181/32763756-89a4e9bc-c93c-11e7-8a28-4648c4bb23ac.png)

**Comment by molq** [comment]
嗯看见了,页面上写着根目录,我去根目录下找了半天.....
