### ISSUE TITLE
Jetty 这个 咋设置 java.lang.IllegalStateException: Form too large: 248817 > 200000

### ISSUE THREAD

**Issue by a100488** [otale/tale#316]
java.lang.IllegalStateException: Form too large: 248817 > 200000 at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:495) at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:433) at org.eclipse.jetty.server.Request.getParameters(Request.java:363) at org.eclipse.jetty.server.Request.getParameter(Request.java:995) at com.blade.mvc.http.wrapper.ServletRequest.query(ServletRequest.java:274) at com.blade.mvc.view.resolve.MethodArgument.getArgs(MethodArgument.java:79) at com.blade.mvc.view.resolve.RouteViewResolve.handle(RouteViewResolve.java:50) at com.blade.mvc.dispatch.DispatcherHandler.routeHandle(DispatcherHandler.java:184) at com.blade.mvc.dispatch.DispatcherHandler.handle(DispatcherHandler.java:94) at com.blade.mvc.dispatch.DispatcherServlet.service(DispatcherServlet.java:39) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.Server.handle(Server.java:564) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) at java.lang.Thread.run(Unknown Source) # # @biezhi

**Comment by a100488** [comment]
发布文章的时候 字数太多 就爆错了

**Comment by dzy0302** [comment]
在TaleConst.java第37行可以设置。
 /**
     * 文章最多可以输入的文字数
     */
    public static final int MAX_TEXT_COUNT = 200000;

**Comment by dzy0302** [comment]
需在开发环境修改后自行重新打包部署运行

**Comment by a100488** [comment]
修改哪个地方  



50330690@qq.com
 
发件人： dzy0302
发送时间： 2017-11-24 10:38
收件人： otale/tale
抄送： Songaw; Author
主题： Re: [otale/tale] Jetty 这个 咋设置 java.lang.IllegalStateException: Form too large: 248817 > 200000 (#316)
需在开发环境修改后自行重新打包部署运行

**Comment by dzy0302** [comment]
修改TaleConst.java文件中第37行的MAX_TEXT_COUNT参数，参数上方有注释，很好理解。

**Comment by a100488** [comment]
没有这一行   是哪个分支  我这个分支是tale-mysql


50330690@qq.com
 
发件人： dzy0302
发送时间： 2017-11-24 10:36
收件人： otale/tale
抄送： Songaw; Author
主题： Re: [otale/tale] Jetty 这个 咋设置 java.lang.IllegalStateException: Form too large: 248817 > 200000 (#316)
在TaleConst.java第37行可以设置。
/**
* 文章最多可以输入的文字数
*/
public static final int MAX_TEXT_COUNT = 200000;

**Comment by dzy0302** [comment]
看了一下，MySQL分支的没有这行，最新的master分支上有，我的是master分支的

**Comment by a100488** [comment]
mysql和master差别好大啊    合一下分支白


50330690@qq.com
 
发件人： dzy0302
发送时间： 2017-11-24 14:43
收件人： otale/tale
抄送： Songaw; Author
主题： Re: [otale/tale] Jetty 这个 咋设置 java.lang.IllegalStateException: Form too large: 248817 > 200000 (#316)
看了一下，MySQL分支的没有这行，最新的master分支上有，我的是master分支的

**Comment by biezhi** [comment]
mysql 版本暂时不维护，等功能优化完毕后再考虑是否重构一下。
