### ISSUE TITLE
我在项目里替换了文章发布的编辑器  使用了国人最喜欢的百度ueditor编辑器  可以把代码合上吗  

### ISSUE THREAD

**Issue by a100488** [otale/tale#317]
![image](https://user-images.githubusercontent.com/12635040/33159433-d6ede1d4-d04d-11e7-8cdb-ec6908df7967.png)
可以让用户自主选择编辑器  用系统的还是 百度编辑器   代码无侵入  只是在项目中加了个包
在文章编辑页加了ueditor的编辑器
![image](https://user-images.githubusercontent.com/12635040/33159539-b33e92c8-d04e-11e7-85b2-6c4be9bd6efa.png)

**Comment by BearMitter** [comment]
國人最喜歡的？別輕易代表我。垃圾百度，切莫插入

**Comment by a100488** [comment]
@BearMitter 你是国人?

**Comment by a100488** [comment]
我这个只是弄出来了个插件  用不用都可以,又不是去替换源代码

**Comment by dongm2ez** [comment]
建议以插件形式发布，而非合入主版本中

**Comment by biezhi** [comment]
该设计风格不适合 `tale`，很抱歉，我们无法同意使用 `ueditor`，感谢你的建议。
