### ISSUE TITLE
新版本的问题

### ISSUE THREAD

**Issue by monsterLin** [otale/tale#318]
貌似有bug，我第一次安装的时候并没有提示有安装的页面，直接可以进入页面，删掉 install.lock这个文件后，在执行下ip:9000/install才出现安装界面- -#

**Comment by jsonwu5** [comment]
同意遇到该问题，控制台有一个js报错，删掉 install.lock这个文件后解决了问题

**Comment by jsonwu5** [comment]
install.js?v=v1.0:80 Uncaught TypeError: Cannot set property 'value' of null
    at install.js?v=v1.0:80
(anonymous) @ install.js?v=v1.0:80

**Comment by biezhi** [comment]
已修复，感谢反馈~
