### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by langmu** [otale/tale#32]
![image](https://cloud.githubusercontent.com/assets/19499544/23346841/d9d5778e-fcd8-11e6-9192-abdbc45094b0.png)

我手动创建了数据库，但启动的时候，提示某个表不存在，你能否b把数据表E-R关系给我，谢谢。

**Comment by biezhi** [comment]
你是否做了如下操作？
1. 下载代码
2. 创建数据库
3. 修改jdbc.properties文件
4. 启动服务

**Comment by biezhi** [comment]
看看这个可以帮到你 https://github.com/otale/tale/blob/master/video.md
