### ISSUE TITLE
页面下面的“一生有所追求.”这个怎么改呢？

### ISSUE THREAD

**Issue by sinnerliu** [otale/tale#323]
我在下图中改了，但是没有生效。
![image](https://user-images.githubusercontent.com/14275089/33819209-373c3f2e-de84-11e7-91ed-3b338b198b73.png)
刷新了页面后，还是显示的是之前的。求指点，谢谢！
![image](https://user-images.githubusercontent.com/14275089/33819184-0b85bdce-de84-11e7-8de0-f32df896fd07.png)

**Comment by alisonY** [comment]
额 我也有这个问题  [https://github.com/otale/tale/issues/287](url)

**Comment by dongm2ez** [comment]
我测试没有问题，也许是缓存问题，你们换个浏览器试下
