### ISSUE TITLE
本地环境问题

### ISSUE THREAD

**Issue by shupan** [otale/tale#326]
把最新的代码拉下来了，发现挺多报错的。 主要是一些对象的报错的。 不知道需要怎么来处理？
前提说下：
1. maven 已经根据pom.xml 拉取了最新的代码了。 
2. 使用的是tomcat服务器，有报错，没法编译打包运行。 
![问题地址](https://ws1.sinaimg.cn/large/006tNc79gy1fmksu2ou6qj31iu072wh9.jpg)

报错截图：

![](https://ws1.sinaimg.cn/large/006tNc79gy1fmksu2ou6qj31iu072wh9.jpg)

**Comment by biezhi** [comment]
感谢你耐心的提问，我觉得可以从 [wiki](https://github.com/otale/tale/wiki) 开始

**Comment by shupan** [comment]
这个我测试了，调试流程可以走通，并且我的本地开发环境也正常的运行了。 但是仍然会有上面的提示。 
详细见我的截图：
![](https://ws2.sinaimg.cn/large/006tNc79gy1fmkvxht5rhj31g209kwhw.jpg)
https://ws2.sinaimg.cn/large/006tNc79gy1fmkvxht5rhj31g209kwhw.jpg

**Comment by biezhi** [comment]
@shupan 这个错误是由于 `lombok` 未加载引起的，导致没有在编译期生成 Getter Setter 方法，你检查一下

1. IDE 是否已经安装 `lombok` 插件
2. 本地重新编译一次看看错误是否会消失 `mvn clean compile`

**Comment by shupan** [comment]
问题已经解决了。非常感谢！ 主要是之前忽略了安装lombok插件。

**Comment by biezhi** [comment]
祝你一路顺风，我关闭这个 `issue` 了。
