### ISSUE TITLE
录制安装使用视频教程

### ISSUE THREAD

**Issue by biezhi** [otale/tale#33]
1. 对于开发者
2. 外网如何部署
3. 常见问题解决

**Comment by LearnerWN** [comment]
请问怎么进行项目的部署？

**Comment by biezhi** [comment]
@LearnerWN 你是什么服务器哦？我下午会录制部署的视频教程

**Comment by YountMan** [comment]
** 还没上传么？  **

**Comment by biezhi** [comment]
https://github.com/otale/tale/blob/master/video.md

**Comment by LearnerWN** [comment]
那请问云服务器上怎么部署？是搜索如何在服务器上部署Maven项目就行吗

**Comment by hmybmny** [comment]
@LearnerWN 如果只是使用的话，云服务器和本地应该没区别，配置好所需的环境后（如 Java， MySQL等），执行 java -jar tale-1.0.jar 即可启动web服务器

**Comment by LearnerWN** [comment]
@hmybmny 那请问文件夹需要放到哪里

**Comment by pkwenda** [comment]
@LearnerWN  放在哪里都可以，在同级目录``` java -jar tale-version.jar ```即可

**Comment by LearnerWN** [comment]
@pkwenda 刚才脑子出坑了 问的这个问题白痴了

**Comment by LearnerWN** [comment]
成功安装 美滋滋

**Comment by biezhi** [comment]
@LearnerWN 为tale点个star吧 😋
