### ISSUE TITLE
可以改成新标签页打开超链接么?大佬?

### ISSUE THREAD

**Issue by jaytangchn** [otale/tale#333]

**Comment by biezhi** [comment]
感谢你的建议，2018人们将得到它。

**Comment by zoujiayu** [comment]
show_tag，输出的是a标签，后面加个target="_blank，就可以新标签，打开超链接了，希望没理解错😂

**Comment by biezhi** [comment]
@zoujiayu 这个在 [这里](https://github.com/otale/tale/blob/master/src/main/java/com/tale/utils/TaleUtils.java#L187) 已经处理了
