### ISSUE TITLE
关于Mrakdown图标的问题

### ISSUE THREAD

**Issue by TonyWang8904** [otale/tale#337]
想在写文章的时候使用图标，请问tale的markdown支持Font Awesome图标吗？
我看见在`友链`页面中使用了`:lock:`这样形式的图标，请问这样具体有哪些图标啊？

**Comment by Mammothill** [comment]
个人认为这是emoji，具体更多的可以查询[emojipedia](https://emojipedia.org/)shortcodes或直接从输入法打出👌
