### ISSUE TITLE
对于文件管理的问题

### ISSUE THREAD

**Issue by EmperorZzl** [otale/tale#339]
对于文件管理，除了限制了大小不能超过20M还有其他的吗？

**Comment by EmperorZzl** [comment]
我上传的时候总是一会能上传上去，一会又不行了。多半是图片，图片大小不会超过1M

**Comment by zoujiayu** [comment]
resources目录下创建个upload文件夹，要上传的文件丢进去，然后再引用

一会行，一会不行，可能是你网络问题，或文件夹权限问题
