### ISSUE TITLE
评论系统的URL

### ISSUE THREAD

**Issue by p1094358629** [otale/tale#343]
我试想 此类的URL提交 `https://html-color-codes.info/chinese/`
但是提交显示 `wrong url format`
从哪里可以修改?

**Comment by static-mkk** [comment]
应该是jquery在序列化的时候处理这个url的时候出现了错误。。
<a href="http://www.kkcoder.cn/upload/2018/02/q0vgj98foih8io1mv6okfeo0c7.png" >debug图片</a>

**Comment by p1094358629** [comment]
大佬过完年解决下呗。。。

**Comment by static-mkk** [comment]
找了好久，发现问题出现在blade的package  com.blade.validator 的ValidatorMiddleware 类 的validateUrl（） 方法。
 该类的url的正则表达式是这样的：
      (https?://(w{3}\\.)?)?\\w+\\.\\w+(\\.[a-zA-Z]+)*(:\\d{1,5})?(/\\w*)*(\\??(.+=.*)?(&.+=.*)?)?        
 这个对于这种url匹配不上。 
而：package com.blade.kit 类 PatternKit 的常量 url 正则表达式则可以匹配 
 URL_REGEX= "^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]";       
所以，只需要把上述： validateUrl（）方法的 正则表达式 改成 下面 URL_REGEX这个即可。

@biezhi 
所以，群主把这个仓库里的正则改一下，应该就解决了。。。。

     <dependency>
            <groupId>com.bladejava</groupId>
            <artifactId>blade-validator</artifactId>
            <version>${blade-validator}</version>
        </dependency>

**Comment by p1094358629** [comment]
不好意思现在才看到,

**Comment by biezhi** [comment]
已修复
