### ISSUE TITLE
启动提示找不到jar包

### ISSUE THREAD

**Issue by blankorange** [otale/tale#345]
报错信息如下：
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
jarfile=
cmd: java -Xms128m -Xmx128m -jar  > ./tale.out < /dev/null &
Error: -jar requires jar file specification

执行命令find / -name 'tale*.jar'也无任何结果

**Comment by zoujiayu** [comment]
我记得lib目录下没tale.jar
执行java -jar tale-least.jar即可运行
需要java运行环境，jre1.8

**Comment by tuzhao** [comment]
可以参考一下我的文章，关于tale升级的。https://tuzhao.org/article/8
