### ISSUE TITLE
页面管理bug

### ISSUE THREAD

**Issue by ioboyo** [otale/tale#346]
在页面管理编辑个人信息后点保存页面会出错，错误提示是该路径已经存在，请重新输入
具体就是当编辑页面管理的时候，第一次点击保存页面的话就提示成功，如果再次点击则提示该路径已经存在，需要退出再次编辑才行！

**Comment by zoujiayu** [comment]
这不是bug(눈_눈)

**Comment by biezhi** [comment]
已修复
