### ISSUE TITLE
端口改成80，启动服务报错

### ISSUE THREAD

**Issue by gqb** [otale/tale#347]
我在resources/app.properties添加一行server.port=80，启动服务器报错
io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989) at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254) at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) at java.lang.Thread.run(Thread.java:748)

**Comment by zoujiayu** [comment]
80端口可能被占用了

**Comment by gqb** [comment]
![image](https://user-images.githubusercontent.com/9876168/36524492-2115091a-17e1-11e8-8781-28dbfabda3e3.png)
并没有被占用，80端口完全不能访问，8080和8081可以访问但是css样式不对

**Comment by zoujiayu** [comment]
你使用的是系统root账户登陆吗，用root账户放行端口，然后在root账户中启动tale看看

**Comment by gqb** [comment]
使用管理员权限启动是可以访问了，但是里面的图片链接还有点击文章链接都使用的是9000端口所以访问不到资源，好像也加载不到css资源

**Comment by zoujiayu** [comment]
进tale后台设置，把博客链接改成现在的，你之前是ip:9000换成现在的，资源就能访问了

**Comment by gqb** [comment]
可以了，谢谢

**Comment by p1094358629** [comment]
我之前遇到过类似的,端口应该是8080.不是80
