### ISSUE TITLE
mysql版本初始化，填写完第一步后点击下一步提示这个是什么原因？应该怎样操作？

### ISSUE THREAD

**Issue by DionQiu** [otale/tale#353]
![image](https://user-images.githubusercontent.com/24718157/37466375-8754db98-2898-11e8-9804-2d88b97446cd.png)

**Comment by zoujiayu** [comment]
数据库连接错误，估计

**Comment by biezhi** [comment]
旧的 `mysql` 版本已不再维护，下一个版本的更新后会出一个修改 `MySQL` 的视频，做了很多兼容，基本不用改动代码。

**Comment by biezhi** [comment]
#378
