### ISSUE TITLE
你好,我在a标签加入网页跳转的url 每次都会拼上我的网站地址 添加哪个标签可以不去拼

### ISSUE THREAD

**Issue by tobin4j** [otale/tale#354]
你好,我在a标签加入网页跳转的url 每次都会拼上我的网站地址 添加哪个标签可以不去拼  谢谢回答

**Comment by zoujiayu** [comment]
A标签代码发出来看看

**Comment by tobin4j** [comment]
比方说我在footer.html添加了一个这个a标签

<p><a href="www.baidu.com">btn</a></p>

页面跳转的路径会变成这个

https://www.libg.top/www.baidu.com  前面是我的网站地址 后面是我要跳转的链接  是在后台管理的编辑模版直接改的

**Comment by zoujiayu** [comment]
把www.baidu.com改成http://www.Baidu.com
