### ISSUE TITLE
昨天更新后，tale首页显示有bug

### ISSUE THREAD

**Issue by wayn111** [otale/tale#358]
![8 sdq 88bo5d ai lh g 7](https://user-images.githubusercontent.com/34181171/38243193-50c61850-3769-11e8-83f2-2975370fc763.png)
首页得路由接收参数为int时，控制台如下：
2018/04/03 18:04:12 ERROR [   worker@threadㄧ7 ] c.b.m.h.DefaultExceptionHandler : Handle exception =>  java.lang.ClassCastException: Cannot cast java.lang.Integer to int
改成Integer即可，文件管理和文章管理都出现了这个问题
env：win10，jdk1.8

**Comment by biezhi** [comment]
你的代码是什么时候更新的？什么分支？

**Comment by wayn111** [comment]
今天最新得dev分支

**Comment by biezhi** [comment]
我晚上会排查这个问题，感谢反馈。

**Comment by biezhi** [comment]
fixed https://github.com/otale/tale/commit/050291d6f08fb0faf4206ca538dad013f7693b8f
