### ISSUE TITLE
首页新增标签和分类tab？

### ISSUE THREAD

**Issue by panjf2000** [otale/tale#363]
首先谢谢作者贡献了这个简洁优秀博客系统，然后我想问一下不知道作者有没有考虑在首页加一个标签库和分类的tab，类似这种：
![image](https://user-images.githubusercontent.com/7496278/38450675-7f57c388-3a54-11e8-9a22-6fe03258c05a.png)
可以方便访问者查看特定分类或者标签的系列文章，谢谢！

**Comment by zoujiayu** [comment]
这个是已经实现了的，只是官方默认主题没有使用。

你看看我这个主题( •̥́ ˍ •̀ू )

https://blog.2aa.win/article/tale-theme-Kratos

**Comment by panjf2000** [comment]
@zoujiayu 哇，厉害啊，不过你可以考虑把这套主题提交给tale项目，以后跟着主版本更新，个人建议。

**Comment by zoujiayu** [comment]
也就
#for(c : categories())
和
#for(t : tags())
将name和count输出
前端写几句样式美化下就可以了，这些函数官方Wiki文档主题制作里面有写的，可以看看✺◟(∗❛ัᴗ❛ั∗)◞✺
