### ISSUE TITLE
JDBC导入properties空指针了

### ISSUE THREAD

**Issue by montycoding** [otale/tale#37]
![image](https://cloud.githubusercontent.com/assets/18158093/23351056/b9132804-fcf9-11e6-812f-39ab9d3eb8aa.png)
不好意思，这样的问题都来问

**Comment by pkwenda** [comment]
@montycoding 具体是如何操作的呢？修改了 ```jdbc.properties```  吗

**Comment by biezhi** [comment]
@montycoding 这个问题很多开发者都遇到了，我出了一个视频教程上面讲了如何操作，正在上传

**Comment by montycoding** [comment]
@pkwenda 
改成了这样
`
db_host=127.0.0.1:3306
db_name=tale
db_user=root
db_pass=123456
`

**Comment by montycoding** [comment]
@biezhi 
多谢

**Comment by biezhi** [comment]
http://git.oschina.net/biezhi/tale/blob/master/donate.md
