### ISSUE TITLE
前端用的是什么ui框架呢

### ISSUE THREAD

**Issue by wuxiongliu1** [otale/tale#38]
博主，你前端ui用的是什么框架呢？还是自己写样式控制？

**Comment by pkwenda** [comment]
@wuxiongliu1 
tale作者前端没有用框架，只是借鉴了一些其他优秀作品作为模板，具体可见项目下方
因为我们要做支持切换多个主题的博客系统，所以借鉴别人开源的是成本最小的。

**Comment by wuxiongliu1** [comment]
恩，设计的很赞
