### ISSUE TITLE
内嵌网易云无法自动播放

### ISSUE THREAD

**Issue by MuenYu** [otale/tale#381]
使用的是wiki中介绍的`[mp3:id]`得方式
同样也试过官方的iframe方式(auto=1仍无效)

**Comment by zoujiayu** [comment]
可能此音乐有版权，无法播放，一般都可自动播放

**Comment by Azureleej** [comment]
可以用，但是不会自动播放啊？？？

**Comment by biezhi** [comment]
自动播放需要修改代码，这并非所有人都希望的，影响用户体验。
