### ISSUE TITLE
能一起参与开发吗

### ISSUE THREAD

**Issue by le0zh0u** [otale/tale#39]
毕业一年多的java后端码农，立志成为全能全栈工程师。之前实习时曾在前端部门进行前端的学习和锻炼，较熟练的使用jquery等框架。后觉得前端变化多端，还是从大学学的比较多的java入手，就成为了java工程师，之前曾自己学习vuejs等前端框架。虽进入github多日，但无建树，看到这个项目想尝试下:)

**Comment by biezhi** [comment]
非常欢迎，可以添加QQ群 1013565 交流
