### ISSUE TITLE
master分支打包出来在谷歌浏览器上不能正常安装

### ISSUE THREAD

**Issue by PhoenixZeng** [otale/tale#397]
在edge倒是可以运行...
在谷歌浏览器各种地地方都有bug

**Comment by PhoenixZeng** [comment]
32位谷歌 66版本正式版

**Comment by PhoenixZeng** [comment]
直接下载wiki里面的版本也是一样的.
不过我是本地启动的 不是在服务器上域名访问,
跟这个有关系吗

**Comment by biezhi** [comment]
😂 当前 master 可以吗？这个问题没遇到过，无法重现。
