### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'tale.t_options' doesn't exist

### ISSUE THREAD

**Issue by it-noob** [otale/tale#40]
![image](https://cloud.githubusercontent.com/assets/12043442/23355050/e5f92b42-fd0e-11e6-9a50-01a204345740.png)

**Comment by YountMan** [comment]
![qq 20170227171045](https://cloud.githubusercontent.com/assets/17265888/23355217/b520db04-fd0f-11e6-90af-65f9865f19f3.png)

**Comment by it-noob** [comment]
@YountMan 这个SQL需要手动执行么？

**Comment by biezhi** [comment]
https://v.qq.com/x/page/x0379l5ttpq.html

**Comment by YountMan** [comment]
再问一句， 你那儿 项目的编码环境 是GBK 么？

**Comment by YountMan** [comment]
@biezhi  再问一句， 你那儿 项目的编码环境 是GBK 么？

**Comment by it-noob** [comment]
@YountMan @biezhi 谢谢，已近搞定。需要手动执行下那个SQL，我以为是直接通过install来执行的，文档中没有提及，抱歉。

**Comment by biezhi** [comment]
@YountMan 好的，有问题继续反馈哦，我会把大家遇到的问题整理成文档和视频发布出来 ❤️

**Comment by it-noob** [comment]
@biezhi 看到介绍直接创建数据库之后，执行main方法，然后访问install就可以，想当然认为跟WordPress安装一样，数据库初始化的脚本会自动执行，所以就没有手动去执行对应的SQL，希望作者在文档中提及下。
