### ISSUE TITLE
大兄弟，卡住了

### ISSUE THREAD

**Issue by fengxiaowei** [otale/tale#401]
下载了代码，在IDEA运行Application，是可以运行的

打包也是可以打的，在target目录生成了tale.jar

但是运行java -jar tale.jar时，报错：Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade

我是菜鸡，请求帮助

**Comment by biezhi** [comment]
@fengxiaowei 嗨，大兄弟。打包后的文件在 `target/dist/tale`，你在这个目录下运行程序就没问题了，遇到问题继续在这条 issue 下留言。

**Comment by pjc516113732** [comment]
@biezhi  我的也是这个问题 解决不了 放在服务器也是这样

**Comment by biezhi** [comment]
@pjc516113732 @fengxiaowei  目前还会遇到这样的情况吗？当前的代码

**Comment by pjc516113732** [comment]
@biezhi  我自己解决了。。
把jar 放在同一级
resource 和lib
