### ISSUE TITLE
markdown支持golang

### ISSUE THREAD

**Issue by panjf2000** [otale/tale#404]
![image](https://user-images.githubusercontent.com/7496278/42130533-af4b207c-7d1a-11e8-8b6f-ef7bf048ff5e.png)

现在的代码引用貌似不支持golang。

**Comment by biezhi** [comment]
![image](https://user-images.githubusercontent.com/3849072/42259349-ad21db2c-7f92-11e8-9399-e675c0570867.png)

用这种方式书写试试

**Comment by panjf2000** [comment]
@biezhi 我截图的博客的最终展示效果，在编辑器里我是按照markdown语法写的：
![image](https://user-images.githubusercontent.com/7496278/42259935-0dab882e-7f95-11e8-8dd6-68c56cb160a8.png)

编辑器的预览似乎是没问题的：
![image](https://user-images.githubusercontent.com/7496278/42259957-1ec78d9c-7f95-11e8-87f5-6dc8360921b1.png)

但是到了博客页面就不行了：
![image](https://user-images.githubusercontent.com/7496278/42259977-32b397b0-7f95-11e8-9b8d-ac42f3b88eb2.png)

**Comment by biezhi** [comment]
我找到了这个问题，是因为默认情况下代码高亮的 `js` 代码没有包含 `go` 代码，我最近会修复这个问题。

**Comment by biezhi** [comment]
fixed https://github.com/otale/tale/commit/38ed9cd554a99b9d69cb0ced38446f99f121d8d5
