### ISSUE TITLE
我的代码 为什么log报错

### ISSUE THREAD

**Issue by wanbao666** [otale/tale#405]
![image](https://user-images.githubusercontent.com/39851813/42258273-84cf8872-7f8d-11e8-92bd-65987ecb65a2.png)
![image](https://user-images.githubusercontent.com/39851813/42258281-8ecac940-7f8d-11e8-951f-add6b8d9b1f9.png)
![image](https://user-images.githubusercontent.com/39851813/42258308-a780ce8a-7f8d-11e8-8b8f-4fede588a173.png)

同步下来的代码里没有这个局部变量。

而且好多实体对象没有get  set 方法啊

**Comment by biezhi** [comment]
@wanbao666 为了简化代码在 `tale` 中使用了 `lombok`，在你的 Eclipse 安装这个插件即可。

见 [wiki](https://github.com/otale/tale/wiki/02.-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E4%B8%8B%E8%BF%90%E8%A1%8C#%EF%B8%8F-%E5%AE%89%E8%A3%85lombok%E6%8F%92%E4%BB%B6)

**Comment by wanbao666** [comment]
请问是什么版本的？lombok



wanbao666@qq.com
 
发件人： 王爵nice
发送时间： 2018-07-04 13:58
收件人： otale/tale
抄送： wanbao666; Mention
主题： Re: [otale/tale] 我的代码 为什么log报错 (#405)
Closed #405.
