### ISSUE TITLE
为什么运行就报错？

### ISSUE THREAD

**Issue by wanbao666** [otale/tale#406]
![image](https://user-images.githubusercontent.com/39851813/42265258-9c4dc1f4-7fa5-11e8-885b-9176985fb7b4.png)
![image](https://user-images.githubusercontent.com/39851813/42265281-a942b70c-7fa5-11e8-837c-17e2e955846b.png)
请大神给看看

**Comment by biezhi** [comment]
@wanbao666 你的代码是什么时候的？可否更新一下尝试，在本地

```bash
git pull
```

**Comment by wanbao666** [comment]
前几天才下载的呢。



wanbao666@qq.com
 
发件人： 王爵nice
发送时间： 2018-07-04 17:14
收件人： otale/tale
抄送： wanbao666; Mention
主题： Re: [otale/tale] 为什么运行就报错？ (#406)
@wanbao666 你的代码是什么时候的？可否更新一下尝试，在本地
git pull

**Comment by biezhi** [comment]
@zoujiayu 可否在 windows 下尝试这个问题，我无法重现它。

**Comment by zoujiayu** [comment]
@biezhi  我这里ok，刚同步的dev

2018/07/04 18:06:37  INFO [   worker@threadㄧ4 ]               c.t.h.BaseWebHook : IP: 127.0.0.1, UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
2018/07/04 18:06:37  INFO [   worker@threadㄧ4 ]    c.b.s.n.HttpServerDispatcher :  200   542ms  GET    /
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Execute SQL => SELECT COUNT(*) FROM t_contents WHERE type = ? AND status = ?
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Parameters  => [post, publish]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Total       => 2 ms, execution: 2 ms, reading and parsing: 0 ms; executed [null]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Execute SQL => SELECT * FROM t_contents WHERE type = ? AND status = ? ORDER BY created DESC LIMIT 0,12
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Parameters  => [post, publish]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Total       => 0 ms, execution: 0 ms, reading and parsing: 0 ms; executed [null]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Execute SQL => SELECT COUNT(*) FROM t_contents WHERE type = ? AND status = ?
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Parameters  => [post, publish]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Total       => 0 ms, execution: 0 ms, reading and parsing: 0 ms; executed [null]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Execute SQL => SELECT * FROM t_contents WHERE type = ? AND status = ? ORDER BY created DESC LIMIT 0,12
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Parameters  => [post, publish]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Total       => 0 ms, execution: 0 ms, reading and parsing: 0 ms; executed [null]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Execute SQL => SELECT COUNT(*) FROM t_contents WHERE status = ? AND type = ?
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Parameters  => [publish, post]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Total       => 0 ms, execution: 0 ms, reading and parsing: 0 ms; executed [null]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Execute SQL => SELECT * FROM t_contents WHERE status = ? AND type = ? ORDER BY created DESC LIMIT 0,8
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Parameters  => [publish, post]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Total       => 15 ms, execution: 0 ms, reading and parsing: 15 ms; executed [null]
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Execute SQL => SELECT COUNT(*) FROM t_comments
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Parameters  => []
2018/07/04 18:06:37 DEBUG [   worker@threadㄧ4 ]                       o.s.Query : Total       => 0 ms, execution: 0 ms, reading and parsing: 0 ms; executed [null]

**Comment by biezhi** [comment]
@wanbao666 你目前还会出现这个问题吗？
