### ISSUE TITLE
本地部署完成后，进入用户端点击文章无法查看详情...

### ISSUE THREAD

**Issue by Soso-zyc8** [otale/tale#41]
本地部署完成后，进入用户端点击文章无法查看详情...

**Comment by biezhi** [comment]
@Soso-zyc8 可以详细说一下你的问题吗？我测试了没有发现

**Comment by Soso-zyc8** [comment]
<div class="navbar-menu">
            <a href="${site_url('/archives')}">归档</a>
            <a href="${site_url('/links')}">友链</a>
            <a href="${site_url('/about')}">关于</a>
        </div>




在前端页面上点解关于，无效。没有反应，然后手动输入localhost:9000/about则可以打开，这是为啥？
其他链接一样。

**Comment by hmybmny** [comment]
你把鼠标放在无效的链接上后看下左下方显示的地址是什么？
![qq_pic_merged_1488194195365](https://cloud.githubusercontent.com/assets/18681240/23359572/c50441f2-fd21-11e6-9f47-e574960da5ad.jpg)

**Comment by biezhi** [comment]
@Soso-zyc8 你可以在你的数据库中查看 `t_options` 表的 `site_url` 记录是什么

**Comment by Soso-zyc8** [comment]
@biezhi  t_options  这个字段的内容为: localhots:9000

**Comment by Soso-zyc8** [comment]
@hmybmny 
![image](https://cloud.githubusercontent.com/assets/8654276/23388788/491f9284-fd9f-11e6-80dc-fb778e23649b.png)

**Comment by Soso-zyc8** [comment]
项目启动运行Appliction Main log信息 
![image](https://cloud.githubusercontent.com/assets/8654276/23388851/997b644c-fd9f-11e6-9ab4-e14ed7e52f75.png)
这个会有影响吗？


还有在浏览器访问主页时的log
![image](https://cloud.githubusercontent.com/assets/8654276/23388875/b541f434-fd9f-11e6-8084-c36816af66a0.png)

**Comment by Soso-zyc8** [comment]
测试了下整个前段页面，只有分类可以点击响应,其他都没反应
后台是正常的。

![image](https://cloud.githubusercontent.com/assets/8654276/23388958/0e64c1ea-fda0-11e6-8dbd-1aaafa6e860f.png)

--------------------------more-----------------------------
这里是页面点击归档、友链、关于的debug信息
![image](https://cloud.githubusercontent.com/assets/8654276/23388998/4bb256de-fda0-11e6-979f-9499c516e9ea.png)

**Comment by pkwenda** [comment]
@Soso-zyc8 UBG已修改，请尝试在```site_url_```  ```ip:port````字段前加```http://```

**Comment by Soso-zyc8** [comment]
@pkwenda    OK 了。

.................. 这Bug，学习了。

**Comment by Soso-zyc8** [comment]
非常感谢

@biezhi @hmybmny @pkwenda
