### ISSUE TITLE
markdown中插入完整的外部链接问题

### ISSUE THREAD

**Issue by aclyyx** [otale/tale#414]
报告一个bug，应该算是bug吧。
在使用markdown编写博客文章时，插入完整的外部链接，文章发布后会加站点地址前缀，导致链接无法打开。

**Comment by aclyyx** [comment]
比如这篇文章: http://blog.aclyyx.com/article/27

**Comment by biezhi** [comment]
@aclyyx 你是如何插入外部链接的？

```bash
[《2小时学会SpringBoot》](https://www.imooc.com/video/13589)
```

这种方式吗？

**Comment by aclyyx** [comment]
使用的是引用式链接。  
第一种：没有问题；
第二种：存在问题中描述的问题；
第三种：脚注，没有显示脚注的信息，基本还是效果与引用式相同，点击超链接没有问题。

效果在此：http://blog.aclyyx.com/article/28

````
* 内联链接  

[百度](https://www.baidu.com)  

* 引用式链接  

[百度][1]  

[1]: "https://www.baidu.com" "Baidu"  

* 脚注  

百度[^链接]  

[^链接]: https://www.baidu.com  
````

**Comment by biezhi** [comment]
@aclyyx 我试了下

```bash
[百度][1]  

[1]: "https://www.baidu.com" "Baidu"  
```

上述方式确实不行，只需要将 `"https://www.baidu.com"` 左右两侧的双引号去除就正常了。

**Comment by aclyyx** [comment]
的确如此
