### ISSUE TITLE
分类问题，只能使用默认分类

### ISSUE THREAD

**Issue by zhaochen55** [otale/tale#417]

**Comment by zoujiayu** [comment]
需要在/admin/category 页面添加分类再去文章页设置文章分类，更新应该会改善

**Comment by zhaochen55** [comment]
![image](https://user-images.githubusercontent.com/10241076/43577898-d1256f44-967f-11e8-9150-660f0a524c1c.png)
已经新建分类，选择了分类，发布文章还是 默认分类，可能是bug吧

**Comment by zoujiayu** [comment]
@zhaochen55
默认主题吗？，tale下载的哪个分支
这个问题我没遇到

**Comment by zhaochen55** [comment]
develop啊，怪怪的，我在一点一点看代码
![tim 20180803085941](https://user-images.githubusercontent.com/10241076/43618586-c047760a-96fb-11e8-877c-fda09176defd.png)

**Comment by zoujiayu** [comment]
@biezhi
