### ISSUE TITLE
点击图片放大高亮实现

### ISSUE THREAD

**Issue by GuoZhaoHui628** [otale/tale#418]
如题，想请教下怎样实现点击图片放大

**Comment by GuoZhaoHui628** [comment]
@dongm2ez 就是普通常见的功能，一篇博客中，如果有图片显示，点击图片，会显示清晰的大图。
好神奇，我翻了下作者的博客，所有文章中都没用到图片....

**Comment by dongm2ez** [comment]
这是一个JS插件，或者一段JS代码实现的功能。

一般原理是页面上是缩略图或者限制大小的图片，鼠标点击或者放置后触发事件请求更清晰的图片或者更大尺寸的图片。

著名的插件有 zoomify.js、jquery zoom等，当然如果网站没有使用这个插件你也可以安装chrome浏览器插件给所有网站的图片都实现这个功能，比如 Imagus

**Comment by zoujiayu** [comment]
js可以实现，这个功能需要主题引入该js
这种效果?
![default](https://user-images.githubusercontent.com/20484791/43577091-7e1e74f0-967d-11e8-8ce9-7331b5998b7b.PNG)

[有兴趣可以看看,有你想要的功能](https://github.com/zoujiayu/tale-theme-Kratos)

**Comment by GuoZhaoHui628** [comment]
@zoujiayu 不是这种，这种是重新开一个页面了，体验不是很好。我在使用
[zoom.js](https://github.com/fat/zoom.js/)
怎么实现不了呢

**Comment by GuoZhaoHui628** [comment]
@dongm2ez 老哥，你用了 `zoom.js` 插件没。我在引入过程中一直报错。
[点击放大](![mark](http://images.bixiaode.com/dream/180802/If0flGBjLh.png?imageslim))
[点击放大](![mark](http://images.bixiaode.com/dream/180802/69E6Bi1cFg.png?imageslim))
![mark](http://images.bixiaode.com/dream/180802/md3JIG53Bi.png?imageslim)

**Comment by zoujiayu** [comment]
@GuoZhaoHui628 
自己写段js给img标签添加target="_blank"
应该可以

**Comment by GuoZhaoHui628** [comment]
@dongm2ez @zoujiayu 谢谢！已经解决。[效果](http://guozh.net/article/15)
