### ISSUE TITLE
master分支如何改造能支持mysql？

### ISSUE THREAD

**Issue by supler** [otale/tale#422]
master分支如何改造能支持mysql？

**Comment by biezhi** [comment]
@supler 抱歉晚回复你，改造成 MySQL 不是很麻烦。

修改为 MySQL 需要注意几个点，tale 的数据库操作库是 [anima](https://github.com/biezhi/anima)。

在项目中需要修改如下几处：

1. 将 SQLite 数据源修改为 MySQL 数据源，在 [Bootstrap](https://github.com/otale/tale/blob/develop/src/main/java/com/tale/bootstrap/Bootstrap.java#L62) 类
2. 修改归档 SQL，在 [SiteService](https://github.com/otale/tale/blob/develop/src/main/java/com/tale/service/SiteService.java#L154) 类
