### ISSUE TITLE
为啥这个web项目是打的jar吧，而不是war吧？

### ISSUE THREAD

**Issue by DerrickYang007** [otale/tale#423]
这个web项目源代码，
我用的myeclipse+maven+tomcat8 处理的。

web项目不都是 打成war包运行的么，怎么项目源码是打成jar包？

我自己在对这个项目进行学习改造。在摸索中。。。初学。

**Comment by biezhi** [comment]
@DerrickYang007 Java 语言编写的软件都可以打成一个 jar 包，包括 web 项目。打成 war 包的项目是因为你只知道基于 Servlet API 开发的 Web 工程，目前 jar 包方式已经趋于流行，代表项目如 SpringBoot、Vert.X、Blade。

如果你初次了解该项目，建议先查看 [wiki](https://github.com/otale/tale/wiki) 和 [视频教程](https://www.bilibili.com/video/av15877070/)，如果遇到什么问题可以在 issue 中提问 😜

**Comment by DerrickYang007** [comment]
好的，多谢。我是想把这个开源项目改成后台web service， 提供api，然后连上我的小程序前台博客。
玩微信小程序。

**Comment by biezhi** [comment]
@DerrickYang007 你简单点可以直接读取 `feed.xml`，相当于 RSS 方式实现。

**Comment by DerrickYang007** [comment]
博主master biezhi,请问feed.xml 是啥？怎么读取？

**Comment by biezhi** [comment]
@DerrickYang007 就是你域名后 + `feed.xml`，如：`http://www.example.com/feed.xml` 。

这里会存放所有的文章，然后你解析 RSS 的链接就可以了，一般都是直接用 RSS 阅读器看的。
