### ISSUE TITLE
导出sql博客数据

### ISSUE THREAD

**Issue by yujintao529** [otale/tale#427]
你好，我的系统里并没有导出数据库这块的功能，请问下，这个是需要自己配置，还是需要自己读tale.db文件呀？
我看你的网站里有这块内容。但是我的系统设置里没有系统备份内容。
![image](https://user-images.githubusercontent.com/6355153/44197445-30fc0800-a171-11e8-9f9d-fd8c16a50b18.png)

**Comment by biezhi** [comment]
这个好像是很早的版本了，你直接备份一下 `resources/tale.db` 就可以了。

**Comment by yujintao529** [comment]
ok~
