### ISSUE TITLE
登录安全问题

### ISSUE THREAD

**Issue by uiwe** [otale/tale#432]
目前密码是明文传输，是否可以加盐和Md5 来避免明文传输。当然如果有https 这个问题可以忽略。

**Comment by biezhi** [comment]
这样做的话意义不大，经过 `md5` 后台无法进行登录校验，如果把加密逻辑放在前端更不安全。一般也没人这么干，更复杂和安全的认证方案在博客系统中并不是很适用，因为这是开源项目即便做了别人一看代码也就知道了。
