### ISSUE TITLE
最新dev版本 编辑文章时，之前设置的标签不显示

### ISSUE THREAD

**Issue by 1943lee** [otale/tale#433]
新建文章的时候设置过几个标签，再进去编辑页面，发现不显示原有标签；仍可以继续加标签，看数据库，发现新的老的标签都在，但是加载时无法展示。

![image](https://user-images.githubusercontent.com/28287600/44902060-93d9cb80-ad3b-11e8-9e40-9785c5fb7827.png)

用同样的数据库，用最新的release版，是正常的。

**Comment by biezhi** [comment]
感谢反馈，正在重现这个问题。
