### ISSUE TITLE
install 验证

### ISSUE THREAD

**Issue by pkwenda** [otale/tale#44]
install 填写 网页url字段修复 url验证或首页跳转连接进行智能处理，用户输入非http://开头请求会打开空白页或404

**Comment by pkwenda** [comment]
i do this😃

**Comment by biezhi** [comment]
我测试了没有遇到这个，而且没有验证网页url，只要输入就可以，因为有的用户输的是ip端口

**Comment by pkwenda** [comment]
@biezhi 
本地测试： 
- 将 ```option``` 表 ```site_url```字段改为：```127.0.0.1```
- 进入127.0.0.1:9000
- 点击一篇博客
![image](https://cloud.githubusercontent.com/assets/14212375/23373182/c2e87efa-fd59-11e6-870f-4dc797af6b73.png)
无```http://```头  chrome下
![image](https://cloud.githubusercontent.com/assets/14212375/23373206/e3b7c88e-fd59-11e6-9aba-8eb5fb2c7db0.png)

我的意思：要么修改前端验证：加上```type="url"```但是必须以正规网站url书写，有局限性。
希望后端出验证
大概这种：
```
 /**
     * 返回网站链接下的全址
     *
     * @param sub 后面追加的地址
     * @return
     */
    public static String site_url(String sub) {
        return site_option("site_url").startsWith("http")?site_option("site_url"):"http://"+site_option("site_url") + sub;
    }
```
或者存储到```site_url```表做验证

我认为若部署到服务器，没有```http://``` 是追加到该网站```"/"```后的```url```，非新的url

**Comment by biezhi** [comment]
我试过，这样 `http://112.332.11.34:9000` 这样的验证不通过

**Comment by pkwenda** [comment]
@biezhi 是的，我修改一下
