### ISSUE TITLE
升级tale版本失败

### ISSUE THREAD

**Issue by panjf2000** [otale/tale#440]
使用./tale-cli upgrade升级tale失败了，更新包下载地址404了，导致升级之后很多本地目录被清空了。。。

**Comment by jasonleelover** [comment]
咋回事啊，我好像也是

**Comment by panjf2000** [comment]
@biezhi 麻烦解答下，现在博客完全挂了

**Comment by biezhi** [comment]
@panjf2000 你再尝试一下

**Comment by panjf2000** [comment]
![image](https://user-images.githubusercontent.com/7496278/45734703-0d1c5e00-bc18-11e8-80f9-5c8ca6d47a0b.png)
我看了下tale-cli的源码，现在这个download_url是对的？

**Comment by biezhi** [comment]
@panjf2000 这是一个未完成的版本，新的下载链接准备做成可配置的，否则 `static.biezhi.me` 这个域名万一挂了就 GG 了。目前你可以看我上面回复的链接。

**Comment by panjf2000** [comment]
好，我晚上回去试试，谢啦大大

**Comment by panjf2000** [comment]
按你说的方法升级之后，有几个问题：
1.博客首页部分文章自定义图片加载错误，应该是新版本在上传文章缩略图的时候会生成一个以thumbnail_为前缀的图片，但是我重新上传文章自定义图片还是没有；
2.最新评论tab加载不出来内容，是空

**Comment by panjf2000** [comment]
按你说的方法升级之后，有几个问题：
1.博客首页部分文章自定义图片加载错误，应该是新版本在上传文章缩略图的时候会生成一个以thumbnail_为前缀的图片，但是我重新上传文章自定义图片还是没有；
2.最新评论tab加载不出来内容，是空；
3.管理后台的文件管理页面，分页按钮无法点击。

**Comment by panjf2000** [comment]
裁剪图的问题，我看了下源码是图片格式的问题，不支持jpeg以外的格式

**Comment by panjf2000** [comment]
管理后台还有一个问题，页面管理那一块，新增的页面点进去编辑，内容是空，但是首页上面是可以点开并且有数据的

**Comment by biezhi** [comment]
@panjf2000 截图的问题修复了，不过你们下载的那个版本未发布，我准备和 #444 一起合并后发布。

---
页面管理的问题我在看

**Comment by Casithy** [comment]
![image](https://user-images.githubusercontent.com/25094969/45805822-1d087080-bcf2-11e8-803e-5e79878d4516.png)
请教一下各位部署install的大佬们，我install完之后加载静态资源跑900端口加载失败是怎么回事？小白，求教

**Comment by panjf2000** [comment]
评论展示不出来，不管是首页的最新评论还是谋篇文章下的评论

**Comment by biezhi** [comment]
> 评论展示不出来，不管是首页的最新评论还是谋篇文章下的评论

新版本中添加了评论审核的功能，所有评论均需要在后台审核通过才会显示。
分页的问题已经修复。
