### ISSUE TITLE
install完毕访问localhost默认的文章静态资源加载失败

### ISSUE THREAD

**Issue by Casithy** [otale/tale#445]
![image](https://user-images.githubusercontent.com/25094969/45806380-7b821e80-bcf3-11e8-80e4-eac3e1bbafd6.png)
请教一下各位部署install的大佬们，我install完之后加载静态资源跑900端口加载失败是怎么回事？小白，求教

**Comment by Casithy** [comment]
额，静态资源的加载端口默认就是900吗？可以修改吗？

**Comment by biezhi** [comment]
1. 默认端口是 `9000` 不是 `900`
2. [如何修改默认端口](https://github.com/otale/tale/wiki/07.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
