### ISSUE TITLE
如何修改在发布文章时给代码着色的样式，原生的不太好看，换成黑色背景的好一些。

### ISSUE THREAD

**Issue by ittqqzz** [otale/tale#447]

**Comment by zoujiayu** [comment]
改模板

**Comment by ittqqzz** [comment]
> 改模板

请问，怎么操作呢？

**Comment by biezhi** [comment]
@ittqqzz 登录博客后台 -> 其他设置 -> 编辑模板。

默认主题使用了 [highlightjs](https://highlightjs.org/) 中的 `default.min.css` 配色，你可以自行修改。
需要修改 `partial/header.html` 文件 HEAD 中引入的 `/static/css/default.min.css` 为你喜欢的。
