### ISSUE TITLE
Markdown的图片注释没有生效

### ISSUE THREAD

**Issue by panjf2000** [otale/tale#448]
在markdown里插入图片，写了图片注释，在最终的文章页面没有展示出来。

**Comment by biezhi** [comment]
![image](https://user-images.githubusercontent.com/3849072/46579278-c19fe780-ca40-11e8-902b-407fbde64aa2.png)
![image](https://user-images.githubusercontent.com/3849072/46579282-cd8ba980-ca40-11e8-9f2e-f73d823f9c0b.png)

你是想在鼠标悬浮的时候显示 title 吗？

**Comment by panjf2000** [comment]
对的

**Comment by panjf2000** [comment]
对了大佬，我上次反馈的新版本tale的几个bug，啥时候能出格release我更新下(；д；)

**Comment by biezhi** [comment]
@panjf2000 有发布哦，我修改了 [wiki](https://github.com/otale/tale/wiki/01.-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Tale) ，以后可以直接使用脚本升级了。
