### ISSUE TITLE
HTTP2获取不到Cookies S_L_ID 值导致登录失败

### ISSUE THREAD

**Issue by zealzhangz** [otale/tale#454]
问题描述：
- 前期使用的Nginx做反向代理使用的HTTP1.1协议，此时一切正常（使用HTTPS）
- 后来装重新编译安装Nginx使用HTTP2协议
- 发现/admin/login登陆后还是跳转到登录界面，看后台日志已经登录成功，简单看了一下代码，写了个日志发现`c.isPresent()`一直是`false`。包括之前登录日志能打出的UA信息，现在也是空了。
- 当然如果我切回HTTP1.1又好了

```java
            Optional<String> c = request.cookie(TaleConst.USER_IN_COOKIE);
            if (c.isPresent()) {
                try {
                    String value = c.get();
                    long[] ids   = HASH_IDS.decode(value);
                    if (null != ids && ids.length > 0) {
                        return Long.valueOf(ids[0]).intValue();
                    }
                } catch (Exception e) {
                    log.error("", e);
                }
            }
```

部分nginx配置：

```
    server {
       listen       443 ssl http2;
       #listen       443 ssl;
       server_name  www.zhangaoo.com;
......
```

简单试了一下也没找到问题原因，应该是`blade`框架里面的问题。还是HTTP2有什么特殊的地方？大佬有想法可以指点一下，我也会再继续研究研究。

**Comment by biezhi** [comment]
感谢你的反馈，我正在重现这个问题

**Comment by biezhi** [comment]
@zealzhangz 我看你目前使用的版本还是很旧的，不妨试试新版的，这个问题是之前 Blade 的一个 bug。
因为你使用 Nginx 的 HTTP2 会出现一个问题就是 HTTP 响应中的 Header 会变成小写，导致获取不到头信息，这个问题修复过了，每次升级记得确认一下 `tale.db` 数据库文件和自己修改的主题 : )

**Comment by zealzhangz** [comment]
@biezhi 升级到2.0.1后的确好了，果然是Header大小写的问题，之前也没注意到
