### ISSUE TITLE
给新Tale提几个bug

### ISSUE THREAD

**Issue by zoujiayu** [otale/tale#456]
1.页面编辑空白，保存内容后前端显示内容，后台F5后按编辑页面，内容空白
![1](https://user-images.githubusercontent.com/20484791/46577623-8cce6900-ca1d-11e8-8f3a-e5dcfd770726.PNG)
2.文章分类问题，编辑页选择了其他分类，文章还是会被自动分类到默认分类，期望默认分类可以删除。
![2](https://user-images.githubusercontent.com/20484791/46577649-fea6b280-ca1d-11e8-9b51-67ec8936f19d.PNG)
![3](https://user-images.githubusercontent.com/20484791/46577650-ffd7df80-ca1d-11e8-8283-3737eabe17d7.PNG)

**Comment by biezhi** [comment]
1. 是 bug
2. 无法重现

**Comment by zhangfeibiao** [comment]
我的也有这个问题，在后台文章编辑页面，所有的内容都是空白的，但是在前端是有内容的，我看了下数据库也是有内容的。
![image](https://user-images.githubusercontent.com/34374831/46589447-33793f00-cadc-11e8-9cbb-943942ac4aff.png)

在自己本地机器上跑没有这个问题，放到服务器上就出现这个问题了，希望官方给予解决下，我们自己跟踪定位这个问题比较慢。
有一点确定的是如果全部拉git的代码是不会有这个问题的，貌似最新代码merge到了我本地的代码之后放到服务器上就会出现上述问题。然而本地是不会出现。

**Comment by biezhi** [comment]
@zhangfeibiao 这个问题已修复了，你可以参考新的 [wiki](https://github.com/otale/tale/wiki/01.-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Tale)，以后使用脚本直接升级就好了。

**Comment by zhangfeibiao** [comment]
> @zhangfeibiao 这个问题已修复了，你可以参考新的 [wiki](https://github.com/otale/tale/wiki/01.-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Tale)，以后使用脚本直接升级就好了。

好的，感谢！

**Comment by zhangfeibiao** [comment]
> @zhangfeibiao 这个问题已修复了，你可以参考新的 [wiki](https://github.com/otale/tale/wiki/01.-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Tale)，以后使用脚本直接升级就好了。

再请问下，如果使用脚本，会不会影响我修改代码呢，比如说我自己要调一下样式或者增加业务逻辑，这个脚本式的控制是否会带来一定影响呢

**Comment by biezhi** [comment]
> > @zhangfeibiao 这个问题已修复了，你可以参考新的 [wiki](https://github.com/otale/tale/wiki/01.-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Tale)，以后使用脚本直接升级就好了。
> 
> 再请问下，如果使用脚本，会不会影响我修改代码呢，比如说我自己要调一下样式或者增加业务逻辑，这个脚本式的控制是否会带来一定影响呢

不会的，该脚本主要是为了方便用户启动、停止、查看日志、运行状态、升级博客的，升级后会自动备份，你可以手动 [复制](https://raw.githubusercontent.com/otale/tale/develop/bin/tool) 脚本源码试试。

**Comment by zhangfeibiao** [comment]
> > > @zhangfeibiao 这个问题已修复了，你可以参考新的 [wiki](https://github.com/otale/tale/wiki/01.-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Tale)，以后使用脚本直接升级就好了。
> > 
> > 
> > 再请问下，如果使用脚本，会不会影响我修改代码呢，比如说我自己要调一下样式或者增加业务逻辑，这个脚本式的控制是否会带来一定影响呢
> 
> 不会的，该脚本主要是为了方便用户启动、停止、查看日志、运行状态、升级博客的，升级后会自动备份，你可以手动 [复制](https://raw.githubusercontent.com/otale/tale/develop/bin/tool) 脚本源码试试。

嗯好的，:smile:

**Comment by zhangfeibiao** [comment]
> @zhangfeibiao 这个问题已修复了，你可以参考新的 [wiki](https://github.com/otale/tale/wiki/01.-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Tale)，以后使用脚本直接升级就好了。

我看了下tool和install.sh的脚本，如果在linux上直接执行是不可以的，CR LF 和 LF的区别导致的，用notepad++转一下就可以

**Comment by zoujiayu** [comment]
第二个问题的原因找到了
在page-category.html
~~~
// 把
#for(article : articles.rows)
// 改成
#for(article : articles(5).rows)
~~~
便出现这个问题
限制每一分类页显示文章数后就会出现
