### ISSUE TITLE
通过修改模板更改代码高亮无效

### ISSUE THREAD

**Issue by ittqqzz** [otale/tale#457]
* 是部分失效，例如改完后，这样了，背景没有变黑，颜色也不全
* 使用的是：monokai-sublime.css

[![error.png](https://i.postimg.cc/MTBH5gS9/error.png)](https://postimg.cc/WF2sbWtZ)

* 本应该是这样的的吧。。

[![QQ_20181007164636.png](https://i.postimg.cc/PJzm3CjV/QQ_20181007164636.png)](https://postimg.cc/BPbLtQt2)

* 还有一个问题就是，修改模板点击保存后提示404

[![QQ_20181007164825.png](https://i.postimg.cc/VvYSN4x4/QQ_20181007164825.png)](https://postimg.cc/vgN8q7H6)

**Comment by biezhi** [comment]
该问题已修复，升级一下即可。
