### ISSUE TITLE
新版本评论审核还没加上？

### ISSUE THREAD

**Issue by panjf2000** [otale/tale#462]
![image](https://user-images.githubusercontent.com/7496278/46675566-46416000-cc11-11e8-8490-afe6f705d9b4.png)
我更新了最新的tale后发现，评论依旧不能展示，上次说新版本里会有评论审核功能，不过似乎在admin后台没有看到？

**Comment by biezhi** [comment]
@panjf2000 你这是旧版本啊

**Comment by biezhi** [comment]
@panjf2000 再试一下，可能是打包有问题。

**Comment by panjf2000** [comment]
我刚才用wget -qO- git.io/fxsWx | bash下载了之后用解压后的tale里面的admin目录替换现有的，但还是一样，评论审核和页面管理的这两个bug依然存在，上次说的那个分页bug倒是没有了

**Comment by biezhi** [comment]
@panjf2000 根目录下的 `tool` 脚本可以直接升级的

**Comment by panjf2000** [comment]
新的评论倒是有一个审核的按钮，但是以前的评论就都没办法展示出来了？

**Comment by tuzhao** [comment]
> 新的评论倒是有一个审核的按钮，但是以前的评论就都没办法展示出来了？

手动将数据库中评论表的字段值改一下就好了。

**Comment by biezhi** [comment]
@tuzhao 这种方式是可以的，所以像置顶文章这种功能要加字段老用户都没法用的 emmm。设计不足，设计不足。。
