### ISSUE TITLE
更新tale最新版本后，后台admin的页面管理的问题

### ISSUE THREAD

**Issue by panjf2000** [otale/tale#463]
在页面管理的tab里，点击进入编辑页面，发现每一个页面的内容都为空，但是博客首页的展示又是正常的，如下：
![image](https://user-images.githubusercontent.com/7496278/46676098-69204400-cc12-11e8-99fd-595ac460cd98.png)
![image](https://user-images.githubusercontent.com/7496278/46676148-82c18b80-cc12-11e8-9992-431af5e3e777.png)

**Comment by zoujiayu** [comment]
这个问题有提过了是bug
没记错已经修复了

**Comment by panjf2000** [comment]
嗯，之前是我提的，但是我刚刚升级到最新之后发现还是一样，是因为还没有合到最新的release里面？

**Comment by biezhi** [comment]
#456
