### ISSUE TITLE
最新版本tale后台admin的编辑模板不可用

### ISSUE THREAD

**Issue by panjf2000** [otale/tale#464]
选择模板html修改后，点击保存修改，无响应，也不生效。

**Comment by zhangfeibiao** [comment]
你这个是路径错了，你把F12按出来就知道了。我是自己修改了前后端代码

**Comment by panjf2000** [comment]
哦哦，我晚上回去试试，谢啦

**Comment by DoubleJee** [comment]
我看了 路径是admin/api/template/save  但是MVC框架的 param注解好像没有绑定上参数。

**Comment by DoubleJee** [comment]
我看了tpl_list.html页面 提交的路径改成admin/api/template/save ，绑定param注解好像没有绑定上参数，tale.post用的是context-type:application/json 格式，所以要么你写form表单序列化提交，要不然你写个实体类 把那俩参数放进去然后@BodyParam绑定。
