### ISSUE TITLE
打成jar包，修改模板，页面代码根目录的生效了，访问却没有生效

### ISSUE THREAD

**Issue by DoubleJee** [otale/tale#466]
之前一个小bug，改了之后开源修改模板了，然后发现页面没生效，把打出来的jar包里面的html修改才生效，jar包同目录的resources，jar包里也有resources，发现jar包里的resources 页面修改才能生效。

**Comment by biezhi** [comment]
已修复 [v2.0.2](https://github.com/otale/tale/releases/tag/v2.0.2)，升级即可。
