### ISSUE TITLE
后台编辑器点击切换异常

### ISSUE THREAD

**Issue by DoubleJee** [otale/tale#468]
富文本编辑器和普通文章编辑器切换出问题，是编辑文章的模块

**Comment by biezhi** [comment]
请描述你的问题是什么？

**Comment by DoubleJee** [comment]
> 请描述你的问题是什么？

就是编辑文章的时候切换富文本编辑器出现bug，导致两个编辑器无法正常切换，然后出现这种bug之后就是会自动保存文章，您可以看一下

**Comment by biezhi** [comment]
@DoubleJee 好的，在发 issue 的时候标题和描述尽量具体表明意思，否则其他人无法知道你要说什么。

**Comment by DoubleJee** [comment]
> @DoubleJee 好的，在发 issue 的时候标题和描述尽量具体表明意思，否则其他人无法知道你要说什么。

好的！支持biezhi哥哥嚯吼。
