### ISSUE TITLE
云主机部署好像有问题

### ISSUE THREAD

**Issue by vinaJc** [otale/tale#47]
down下release的zip部署到阿里云和conoha上，运行jar包后不能正确打开。访问网址chrome显示连接被拒绝。在本地部署没问题。比对了一下本地，启动过程应该没报错。
配置
阿里云：
oracle jdk 1.8 （121）
ubuntu 16.04 x64
mysql 5.7

conoha（Japan）
openjdk 1.8（121）
centos x64
mysql 5.7

本地：
win10 x64
oracle jdk 1.8（121）
mysql 5.6

**Comment by biezhi** [comment]
你的tale程序是什么时候下载的？

**Comment by vinaJc** [comment]
看过了，今天上午在用户指南里那个连接下载的。  另外dcd8924后我clone了项目，在idea里也没办法运行。 细节早些时候发邮件给你的gamil了。

**Comment by biezhi** [comment]
我邮件收到了，你下载最新的试试，或者加入QQ群讨论，我现在在优化细节
