### ISSUE TITLE
v2.0.2版本bug 反馈

### ISSUE THREAD

**Issue by tuzhao** [otale/tale#473]
今天尝试在本地用源码替换的方式升级到v2.0.2,出现了下面两个问题：
1.位置问题
[
![screenshot from 2018-10-20 20 33 14](https://user-images.githubusercontent.com/9989910/47255676-6ee61700-d4a7-11e8-9ce9-e91fe3d8ef54.png)

2. 文件找不到异常
在路径resources/templates/admin下报找不到article.html

**Comment by biezhi** [comment]
如果没有做特殊修改的话可以备份下数据库  `tale.db` 其他都可以覆盖的。
