### ISSUE TITLE
你好，开发者秘籍有很多图片过期

### ISSUE THREAD

**Issue by disfleet** [otale/tale#478]
https://dev-cheats.com/  这个网站有很多图片过期，麻烦更新下哈   感谢感谢

**Comment by os7blue** [comment]
没钱维持服务器了，要不你捐赠一波

**Comment by zaoangod** [comment]
> 没钱维持服务器了，要不你捐赠一波

我有一个腾讯云的服务器 ,  还有一年时间 , 可以捐赠给你们

**Comment by os7blue** [comment]
逗你玩的

**Comment by biezhi** [comment]
大家可以去 https://examples.codesofun.com/ 看类似的内容，dev-cheats 没有精力维护了，很抱歉。
