### ISSUE TITLE
cdn配置错误导致整个后台系统瘫了

### ISSUE THREAD

**Issue by zhoriya** [otale/tale#487]
![image](https://user-images.githubusercontent.com/26195410/48472885-33363700-e832-11e8-8d6e-8a52f7e56085.png)
如图，因为不小心把cdn配置错了，导致所有的后台管理系统的css，js都加载失败，不能再进行cdn的修改了，不知道有没有其他方法能修复这个cdn地址？尝试过修改sqlLite数据库中的数据，重启后还是不行，最后只能删掉重新安装了。

**Comment by biezhi** [comment]
CDN 配置错误确实会导致后台的样式无法加载，这个可以在后台添加一个 URL 访问后恢复 CDN。
修改 SQLite 应该是没问题的，可能修改的语句不对，试试：

```sql
update t_options set cdn_url = '/static/admin';
```

**Comment by zhoriya** [comment]
> CDN 配置错误确实会导致后台的样式无法加载，这个可以在后台添加一个 URL 访问后恢复 CDN。
> 修改 SQLite 应该是没问题的，可能修改的语句不对，试试：
> 
> ```sql
> update t_options set cdn_url = '/static/admin';
> ```

谢谢，希望能有一个url直接修复这个问题，我的问题已经解决，至于修改数据库没生效我想应该是我下载了sqlite的db文件，在本地修改后忘记上传上去了
