### ISSUE TITLE
丰富搜索功能

### ISSUE THREAD

**Issue by ittqqzz** [otale/tale#490]
### :bulb:可否添加全文搜索？
* 光搜索标题感觉不够。
* 有时候需要根据记忆中谋篇文章内容来查询某一篇文章时就捉襟见肘了。

**Comment by biezhi** [comment]
@ittqqzz 全文检索的技术实现有些麻烦，比如 solr 或 es 实现的话会让这个项目更臃肿，部署起来也很吃力，这样使用者反而不能接受。如果有好的实现方式可以继续讨论，我目前还没好想法。
