### ISSUE TITLE
忘记管理密码怎么办？？

### ISSUE THREAD

**Issue by HuashiHou** [otale/tale#496]

**Comment by biezhi** [comment]
@HuashiHou 你目前可以进入 SQLite 数据库直接修改密码，未来加入邮件配置可以通过邮箱找回。

密码规则是：`password = md5(username + password)`

[在线 md5](http://tool.chinaz.com/tools/md5.aspx)

```shell
cd tale/resources
sqlite3 tale.db
update t_users set password = '********' where username = '';
```

**Comment by HuashiHou** [comment]
Thanks 差的就是这个MD5规则
