### ISSUE TITLE
音乐播放不了

### ISSUE THREAD

**Issue by zokzy** [otale/tale#514]

**Comment by dongm2ez** [comment]
请详细描述问题，需要更详细的描述

**Comment by zokzy** [comment]
https://tale.biezhi.me/article/15

这个是网站，那个音乐点击播放的时候没有反应啊

**Comment by dongm2ez** [comment]
我查看了这些音乐，除了第三首，其他国外音乐都因为版权保护，网易云音乐不再能生成外链分享，也就是说资源只能在网易本站播放。

这并不是这个程序的错误，而是网易云音乐的问题

**Comment by zokzy** [comment]
......就是说我要换音乐了，我安装了你们的博客，怎么知道在网易云上这些能不能播啊

**Comment by dongm2ez** [comment]
这个我们无法控制，只能说网易他们优化，因为实际上网易的外链音乐是在网站里嵌入了一个iframe，也就是嵌入了网易的网页，这是内容问题，和这个程序本身没有关系

**Comment by zoujiayu** [comment]
网易云版权限制，有些歌是无法创建外链播放的，关闭issues了，还有问题可以继续提问。
