### ISSUE TITLE
tale部署一段时间使用http后改用https，会让浏览器报不安全

### ISSUE THREAD

**Issue by flycat0112** [otale/tale#530]
tale部署一段时间使用http后改用https，以前的文件的图片保存都是使用http，并且保存在数据库中。这样的设计不应该让其影响到home页面。
一、如果不考虑图片版权的问题的解决方案：
现象是：
只要文章中有一个文章的图片使用了http，直接影响到/home页面的安全性。
处理逻辑建议：
在保存文章的时候，判断<img>中是否使用http头并且不是本站的图片，如果是，就下载到服务器来。重新替换。
二、考虑到图片版权的问题的解决方案，至少不让影响到/home页面的缩略图，不安全只在那个文章中出现。
这个是一个bug，因为我没有替换内容的时候/home页面安全，我内容替换成https的时候，/home的不安全解决了。

**Comment by flycat0112** [comment]
我看本地有缩略图的，这个应该使用项目配置的网站配置走，不应该使用内容，我想这里面应该还有性能问题吧。

**Comment by callmeioy** [comment]
> tale部署一段时间使用http后改用https，以前的文件的图片保存都是使用http，并且保存在数据库中。这样的设计不应该让其影响到home页面。
> 一、如果不考虑图片版权的问题的解决方案：
> 现象是：
> 只要文章中有一个文章的图片使用了http，直接影响到/home页面的安全性。
> 处理逻辑建议：
> 在保存文章的时候，判断中是否使用http头并且不是本站的图片，如果是，就下载到服务器来。重新替换。
> 二、考虑到图片版权的问题的解决方案，至少不让影响到/home页面的缩略图，不安全只在那个文章中出现。
> 这个是一个bug，因为我没有替换内容的时候/home页面安全，我内容替换成https的时候，/home的不安全解决了。

你是怎么换https的，我也想换，不知道怎么换

**Comment by flycat0112** [comment]
就是申请免费的证书，另外使用nginx来做https的反向代理，将https转换成http给tale

**Comment by flycat0112** [comment]
证书配置都是用nginx来做的
