### ISSUE TITLE
我想把tale作为systemd启动，我自己写的service，启动后退出。不知道什么问题

### ISSUE THREAD

**Issue by flycat0112** [otale/tale#531]
操作系统：
    uname : linux 3.10.0-514.26.2.el7.x86_64
     系统：centos7.3

我想把tale作为systemd启动，我自己写的service，启动后退出。不知道什么问题。
[Unit]
  2 Description=tale
  3 [Service]
  4 Type=forking
  5 ExecReload=/usr/bin/bash /opt/tale/tale/tool.sh reload
  6 ExecStart=/usr/bin/bash /opt/tale/tale/tool.sh start
  7 ExecStop=/usr/bin/bash /opt/tale/tale/tool.sh stop
  8 [Install]
  9 WantedBy=multi-user.target

systemctl status tale

● tale.service - tale
   Loaded: loaded (/etc/systemd/system/tale.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Sat 2019-01-26 21:25:23 CST; 3s ago
  Process: 2773 ExecStop=/usr/bin/bash /opt/tale/tale/tool.sh stop (code=exited, status=0/SUCCESS)
  Process: 2768 ExecStart=/usr/bin/bash /opt/tale/tale/tool.sh start (code=exited, status=0/SUCCESS)

Jan 26 21:25:22 izj6cgykrq171a8wb4394uz systemd[1]: Starting tale...
Jan 26 21:25:22 izj6cgykrq171a8wb4394uz bash[2768]: Starting tale ...
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2768]: [Failed]
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: ================================
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: warn: tale is not running
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: ================================
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz systemd[1]: Started tale.

是我的脚本有问题吗

**Comment by Linindoo** [comment]
日志呢？logs文件夹里面应该有日志的吧

**Comment by flycat0112** [comment]
日志上面 没有error

**Comment by flycat0112** [comment]
Jan 26 21:25:19 izj6cgykrq171a8wb4394uz systemd[1]: Configuration file /etc/systemd/system/shadowsocks.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 26 21:25:19 izj6cgykrq171a8wb4394uz systemd[1]: Configuration file /usr/lib/systemd/system/eni.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Jan 26 21:25:19 izj6cgykrq171a8wb4394uz polkitd[394]: Unregistered Authentication Agent for unix-process:2745:186645 (system bus name :1.38, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jan 26 21:25:22 izj6cgykrq171a8wb4394uz polkitd[394]: Registered Authentication Agent for unix-process:2762:186929 (system bus name :1.39 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jan 26 21:25:22 izj6cgykrq171a8wb4394uz systemd[1]: Starting tale...
Jan 26 21:25:22 izj6cgykrq171a8wb4394uz bash[2768]: Starting tale ...
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2768]: [Failed]
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: ================================
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: warn: tale is not running
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: ================================
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz polkitd[394]: Unregistered Authentication Agent for unix-process:2762:186929 (system bus name :1.39, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jan 26 21:25:23 izj6cgykrq171a8wb4394uz systemd[1]: Started tale.
Jan 26 21:25:26 izj6cgykrq171a8wb4394uz systemd[1]: Configuration file /etc/systemd/system/tale.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 26 21:26:43 izj6cgykrq171a8wb4394uz sshd[2326]: Received disconnect from 182.149.161.234: 11: disconnected by user
Jan 26 21:26:43 izj6cgykrq171a8wb4394uz sshd[2326]: pam_unix(sshd:session): session closed for user root
Jan 26 21:30:01 izj6cgykrq171a8wb4394uz systemd[1]: Started Session 6 of user root.
Jan 26 21:30:01 izj6cgykrq171a8wb4394uz systemd[1]: Starting Session 6 of user root.
Jan 26 21:30:01 izj6cgykrq171a8wb4394uz CROND[2823]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Jan 26 21:30:01 izj6cgykrq171a8wb4394uz postfix/sendmail[2826]: fatal: parameter inet_interfaces: no local interface found for ::1

**Comment by callmeioy** [comment]
> 操作系统：
> uname : linux 3.10.0-514.26.2.el7.x86_64
> 系统：centos7.3
> 
> 我想把tale作为systemd启动，我自己写的service，启动后退出。不知道什么问题。
> [Unit]
> 2 Description=tale
> 3 [Service]
> 4 Type=forking
> 5 ExecReload=/usr/bin/bash /opt/tale/tale/tool.sh reload
> 6 ExecStart=/usr/bin/bash /opt/tale/tale/tool.sh start
> 7 ExecStop=/usr/bin/bash /opt/tale/tale/tool.sh stop
> 8 [Install]
> 9 WantedBy=multi-user.target
> 
> systemctl status tale
> 
> ● tale.service - tale
> Loaded: loaded (/etc/systemd/system/tale.service; enabled; vendor preset: disabled)
> Active: inactive (dead) since Sat 2019-01-26 21:25:23 CST; 3s ago
> Process: 2773 ExecStop=/usr/bin/bash /opt/tale/tale/tool.sh stop (code=exited, status=0/SUCCESS)
> Process: 2768 ExecStart=/usr/bin/bash /opt/tale/tale/tool.sh start (code=exited, status=0/SUCCESS)
> 
> Jan 26 21:25:22 izj6cgykrq171a8wb4394uz systemd[1]: Starting tale...
> Jan 26 21:25:22 izj6cgykrq171a8wb4394uz bash[2768]: Starting tale ...
> Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2768]: [Failed]
> Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: ================================
> Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: warn: tale is not running
> Jan 26 21:25:23 izj6cgykrq171a8wb4394uz bash[2773]: ================================
> Jan 26 21:25:23 izj6cgykrq171a8wb4394uz systemd[1]: Started tale.
> 
> 是我的脚本有问题吗

是不是你marven编译打包改了项目（groupid name）名，tale-lates-jar  如果是这样的话，tool.sh中的文件就要相应的改成你的 ，

**Comment by Linindoo** [comment]
![image](https://user-images.githubusercontent.com/26195410/51879390-2bf0e500-23ae-11e9-8819-ed7c6a38140f.png)
如图，修改tool脚本，尝试切换路径试试,不过后续还会有其他问题，你自己多多尝试，最好tool脚本也自己写吧

**Comment by flycat0112** [comment]
我shell不好，尴尬，初学。我会尝试一下，谢谢。
