### ISSUE TITLE
进入首页很慢

### ISSUE THREAD

**Issue by zealzhangz** [otale/tale#549]
我的个人博客：

https://zhangaoo.com
版本：2.0.1

发现进入首页很慢，需要20秒左右，查看Nginx日志发现也是要等20秒左右请求才能到后台。
然后直接curl 请求http://127.0.0.1:9000同样很慢，一直找不到原因
但是直接加载文章或者静态资源速度确实正常的，好像就只有首页慢，并且好像是最近一段时间才变慢的，以前一直是好了，有点懵逼。看看作者能不能给些排查的建议。

**Comment by zoujiayu** [comment]
## tale和nginx表示不背锅！！！
### 主页文章缩略图文件太大了
#### 主页还加载了音频文件耗时1.7ms
##### 你阿里云1m小水管加载不来的
RT.
![捕获](https://user-images.githubusercontent.com/20484791/56072499-2a8a6280-5dca-11e9-91d0-3dd39bbb5192.PNG)

**Comment by zoujiayu** [comment]
给你回复了，翻一下邮件通知
误删comment了 emm

**Comment by zealzhangz** [comment]
老哥，啥邮件，没收呀。你的意思是我误删前端的代码了？我来检查一下

**Comment by zealzhangz** [comment]
> 给你回复了，翻一下邮件通知
> 误删comment了 emm

老哥啊。我还是没找到原因啊，请明示，你说的邮件我也收到呀
