### ISSUE TITLE
一个反射型的xss漏洞

### ISSUE THREAD

**Issue by thiscodecc** [otale/tale#569]
搜索处没有对html标签进行过滤,在火狐浏览器输入url:
**http://127.0.0.1:9000/search/asd%3Cimg%20src=%22x%22%20onerror=%22alert('xss')%22%3E**

<img width="883" alt="xss" src="https://user-images.githubusercontent.com/55778895/66394834-a7f4ff80-ea08-11e9-8675-509902daa26a.png">

**Comment by zealzhangz** [comment]
试了一下Chrome没有这个问题

**Comment by thiscodecc** [comment]
> 试了一下Chrome没有这个问题

这个地方xss漏洞是存在,是被chrome 浏览器自身过滤了,在Firefox浏览器可以看到.
刚刚提交了一个在chrome下也有的xss漏洞. #570

**Comment by zoujiayu** [comment]
该问题在Chrome可以被复现，解决方法：
com.tale.controller.IndexController  76行后添加
~~~
keyword = (TaleUtils.cleanXSS(keyword));
~~~
