### ISSUE TITLE
小白问一句，在本地安装的时候网站地址填什么？

### ISSUE THREAD

**Issue by maoturing** [otale/tale#57]
![image](https://cloud.githubusercontent.com/assets/12975918/23396222/ac8e9832-fdcd-11e6-9ebf-5a4d9d31dceb.png)

**Comment by biezhi** [comment]
http://127.0.0.1:9000

**Comment by maoturing** [comment]
@biezhi  我这样设置了，进了主页点链接都有问题
![image](https://cloud.githubusercontent.com/assets/12975918/23405456/40605218-fdf5-11e6-8757-24263dfe3d86.png)
图中显示有地址，但是点击之后就会跳到空白页about:blank，点击友链，归档都是这样。

**Comment by biezhi** [comment]
@maoturing 查看一下你的 `t_options` 表的 `site_url` 数据，原因是因为你没有加 `http://`

**Comment by maoturing** [comment]
原来如此，好尴尬。。。
