### ISSUE TITLE
HTTPS 的处理

### ISSUE THREAD

**Issue by hmybmny** [otale/tale#66]
https://github.com/otale/tale/blob/master/src/main/java/com/tale/controller/InstallController.java#L106-L108
这里是否应当考虑下对 HTTPS 的处理？

**Comment by pkwenda** [comment]
不填写```http```头，自动添加```http://```
用户填写了```https```那自然不用处理

**Comment by hmybmny** [comment]
Get.

**Comment by pkwenda** [comment]
😄

**Comment by biezhi** [comment]
不过我觉得这个不用处理，自己是https填对就可以了，我们无法处理
