### ISSUE TITLE
主题素材路径错误，导致无法加载

### ISSUE THREAD

**Issue by Max-Null** [otale/tale#75]
com.tale.ext.Commons下的
    public static String theme_url(String sub) {
        return Commons.site_url(BaseController.THEME + sub);
    }
将会返回错误路径
改为：
    public static String theme_url(String sub) {
        return Commons.site_url( "/templates/" + BaseController.THEME + sub);
    }
就行了

**Comment by trytrytryiii** [comment]
昨晚在家里发现了，修改完忘了提交pr，现在又改了一遍= =
