### ISSUE TITLE
为何博客文章的markdown格式解析后字体都没有变化呢？

### ISSUE THREAD

**Issue by zhisheng17** [otale/tale#83]
**我看还是标准的markdown格式的文章，没有渲染后的展示效果。** @biezhi

**Comment by zhisheng17** [comment]
![sp20170302_180759](https://cloud.githubusercontent.com/assets/10086212/23502550/34ae4f18-ff73-11e6-938e-d40ce6aa031f.png)

**Comment by biezhi** [comment]
这个是样式渲染的，你可以在标题上右击查看元素可以看到是H1, H2这种标签就是ok的，这里的样式我使用了 `pingshu` 的，如果你觉得不够好看，也可以找到对应的 `class` 进行修改

**Comment by pkwenda** [comment]
你是说多以一个蓝色的```#```吗？

**Comment by zhisheng17** [comment]
是的，感觉多了一个 '#'  之后，不好看了。 @biezhi @pkwenda

**Comment by zhisheng17** [comment]
是的，感觉多了一个 ```#``` 之后，不好看了。 @biezhi @pkwenda

**Comment by biezhi** [comment]
@zhisheng17 这个可以自己修改主题哦，tale提供了一套默认的，当然不会每个人都喜欢的，我们会慢慢推出更多好看的优秀主题。

**Comment by zhisheng17** [comment]
ok，谢谢，后期持续关注。 @biezhi
