### ISSUE TITLE
发布包可以用war包方式发布吗

### ISSUE THREAD

**Issue by dongm2ez** [otale/tale#88]
如题，war包更利于用tomcat部署

**Comment by biezhi** [comment]
不可以哦，我们会推出使用脚本和命令的方式启动，无需tomcat，因为框架内部嵌入了web服务器了。

**Comment by dongm2ez** [comment]
那如何配合nginx进行工作，虚拟路径如何配置

**Comment by biezhi** [comment]
这里有个视频讲了如何操作：https://v.qq.com/x/page/b0379544hqe.html
