### ISSUE TITLE
MarkDown编辑表格时显示出现问题

### ISSUE THREAD

**Issue by LoenDou** [otale/tale#90]
在预览时显示正常
![image](https://cloud.githubusercontent.com/assets/19473247/23534750/f016f468-fff4-11e6-81a5-fdb02d36398a.png)
但是在文章发布后显示出现问题
![image](https://cloud.githubusercontent.com/assets/19473247/23534771/1443062e-fff5-11e6-8c97-8e991134871f.png)

**Comment by biezhi** [comment]
感谢反馈
