### ISSUE TITLE
建议使用更语义化的版本号

### ISSUE THREAD

**Issue by dongm2ez** [otale/tale#91]
版本号命名方式：主版本号.次版本号.修订号 
1） 主版本号：当做了不兼容的 API 修改，或者增加了能改变产品方向的新功能。 
2） 次版本号：当做了向下兼容的功能性新增（新增类、接口等）。
3） 修订号：修复 bug，没有修改方法签名的功能加强，保持 API 兼容性。

**Comment by biezhi** [comment]
@dongm2ez 感谢，好主意。
